In [5]:
import pandas as pd

P_record = pd.read_csv("E:\\code\\patient_records.csv")
P_record.head(1)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19

In [6]:
P_record.isna().sum()

patient_id              0
first_name              0
last_name               0
gender                  0
age                     0
blood_type             55
state                   0
smoking_status         52
insurance_type          0
primary_condition       5
height_cm              53
weight_kg              48
systolic_bp             0
diastolic_bp            0
heart_rate_bpm          0
last_admission_date     0
dtype: int64

In [33]:
P_record['height_cm'].unique()

array([152.3, 183.2, 178.1, 171.5, 169.7, 181.8, 180.1, 179.6, 172.6,
       164.5,   nan, 176.2, 166.1, 179.3, 184.6, 160.5, 165.4, 172.9,
       162.8, 186.8, 172.2, 173.3, 185.6, 163.5, 167.1, 155.5, 166.3,
       153.1, 175.5, 165.2, 167. , 175.6, 156.6, 170. , 175. , 150.2,
       174.8, 151.3, 166.8, 156.4, 182.3, 151.5, 169.3, 163.9, 153. ,
       148.1, 157.6, 162.2, 176. , 181. , 179. , 166.5, 143.7, 171.9,
       182.7, 180.3, 156.1, 162.7, 187.3, 153.8, 156.5, 177.4, 163.7,
       156.2, 183.3, 164.2, 167.8, 182. , 176.9, 162.9, 182.5, 182.6,
       149.2, 173.5, 157.7, 170.6, 154.5, 163.3, 160. , 163. , 167.3,
       157.8, 183.7, 185.9, 166.4, 162.5, 166.2, 175.2, 155.6, 175.1,
       173.8, 180.7, 166.9, 159.4, 189.1, 152.7, 153.7, 173.7, 184.2,
       169.9, 178. , 148. , 149.3, 175.8, 152.5, 155.2, 173.1, 178.6,
       173.4, 165.8, 157.1, 173.6, 174.1, 171.1, 156.3, 174.9, 168. ,
       163.2, 165.1, 161.1, 158.1, 164.7, 184.1, 178.5, 151.6, 181.5,
       142.8, 179.2, 183.9, 159.3, 185.5, 145.7, 164.3, 163.8, 179.5,
       177.5, 176.6, 147.3, 178.4, 155.1, 165.9, 171.6, 167.2, 164.6,
       165. , 156.7, 171.2, 154.7, 156.8, 184.5, 168.6, 170.1, 147.9,
       162. , 146.5, 171.7, 180.8, 161.4, 145.6, 158. , 157. , 175.4,
       140.8, 177. , 152. , 182.4, 169. , 179.9, 195.3, 172.8, 161.7,
       142.7, 151.2, 183.5, 174.6, 166. , 164. , 162.3, 189.3, 172.4,
       157.3, 160.8, 172. , 168.5, 192.1, 179.8, 153.6, 181.7, 162.4,
       176.5, 202.4, 160.6, 155. , 158.6, 172.7, 172.5, 163.4, 187.8,
       172.3, 158.9, 141.5, 163.1, 161.2, 165.3, 186.7, 164.1, 171.4,
       162.1, 151. , 155.9, 169.8, 178.8, 150.1, 154.3, 167.5, 160.4,
       169.6, 159.7, 173.2, 176.3, 177.3, 154.8, 136. , 159.8, 148.3,
       161.5, 172.1, 167.7, 174. , 168.9, 159.9, 174.4, 157.9, 149.5,
       177.6, 168.8, 170.5, 157.2, 169.1, 184.8, 161.8, 160.7, 179.1,
       159.2, 177.2, 157.4, 166.6, 191.6, 170.3, 167.4, 160.3, 159.1,
       176.8, 162.6, 168.1, 149.4, 154.1, 184.4, 158.4, 164.9, 186. ,
       135.4, 163.6, 180. , 188.9, 169.5, 158.8, 165.7, 155.8, 169.2,
       187.7, 145.9, 200.3, 180.2, 174.3, 174.7, 158.7, 155.4, 176.1,
       151.9, 168.4, 153.9, 191.5, 152.6, 147.7, 167.6, 159.6, 164.8,
       151.1, 155.3, 182.1, 166.7, 168.7, 165.6, 175.3, 144. , 189.7,
       176.7, 148.6, 171. , 161.9, 164.4, 197.6, 181.4, 170.7, 194.8,
       193.7, 159.5, 149.9, 152.8, 188.4, 188.2, 167.9, 158.3, 158.2,
       160.2, 177.9, 181.1, 188.8, 180.5, 184.3, 185.4, 186.4, 174.5,
       161.3, 158.5, 149.7, 165.5, 186.5, 178.7, 147.8, 139.7, 154.4,
       178.3, 179.4, 195. , 173.9, 141.8, 147.1, 183.4, 160.9, 150.9,
       176.4, 177.8, 187.5, 174.2, 154.2, 156.9, 190.5, 144.7, 180.4,
       197. , 168.2, 147.6, 185.2, 161. , 150.3, 147.5, 150.4, 196.3,
       177.7, 186.1, 156. , 155.7, 137.2, 142.6, 170.4, 149.8, 154.6,
       153.3, 198.6, 154. , 150.8, 181.2, 173. , 149.1, 148.2, 160.1,
       147.4, 159. , 183.1, 188.6, 161.6, 152.4, 157.5, 170.8, 187.6,
       153.5, 187.9, 175.9, 153.4, 146.7, 179.7, 178.2, 140.3, 185.3,
       192.6, 180.6, 146.6, 177.1])

In [34]:
P_record[(P_record['height_cm'].isna()) | (P_record['height_cm'].isin(['NaN']))]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
10,PT100010,Jennifer,Williams,Female,50,A+,MA,Never,Medicare,Hypertension,NaN,77.8,117,95,66,2024-03-05
74,PT100074,Michael,Kowalski,Female,9,O-,GA,Current,Private,Obesity,NaN,60.6,123,87,87,2024-06-06
174,PT100174,Patricia,Patel,Female,73,A+,MA,Former,Medicare,Anxiety Disorder,NaN,88.2,98,66,84,2025-06-16
204,PT100204,Karen,Thomas,Female,72,A+,CA,Current,Private,Anxiety Disorder,NaN,NaN,129,78,82,2024-11-01
224,PT100224,Thomas,Silva,Female,87,B-,CA,Never,Medicare,Type 2 Diabetes,NaN,79.9,104,91,88,2023-04-06
227,PT100227,Yuki,Lee,Male,0,B+,MI,NaN,Private,Depression,NaN,45.6,110,72,79,2023-12-25
230,PT100230,John,Gonzalez,Female,88,A+,NC,Never,Private,Obesity,NaN,106.6,135,87,91,2023-08-12
253,PT100253,David,Johnson,Female,35,O+,MA,NaN,Medicare,Depression,NaN,74.2,150,77,59,2023-12-02
269,PT100269,Barbara,Brown,Female,91,AB-,PA,Never,Private,GERD,NaN,63.0,108,77,87,2025-07-08
274,PT100274,Fatima,Kowalski,Male,88,B+,MA,Former,Private,GERD,NaN,81.9,93,77,76,2023-08-28
275,PT100275,Michael,Martin,Female,56,O+,GA,Former,Medicare,Chronic Kidney Disease,NaN,70.7,105,107,61,2024-10-26
277,PT100277,Michael,Patel,Male,83,A+,CA,Never,Private,Type 2 Diabetes,NaN,82.1,88,68,55,2024-02-09
408,PT100408,William,Smith,Female,75,A+,FL,Never,Private,Obesity,NaN,76.1,143,61,74,2024-08-06
424,PT100424,Richard,Williams,Male,58,O-,NJ,Never,Private,Type 2 Diabetes,NaN,72.9,133,85,78,2025-05-08
427,PT100427,Priya,Brown,Male,89,A+,NC,Current,Private,Type 2 Diabetes,NaN,69.8,130,72,74,2024-12-14
432,PT100432,Carlos,Chen,Male,28,A+,OH,Current,Private,Atrial Fibrillation,NaN,57.2,101,90,79,2023-06-14
469,PT100469,Richard,Wilson,Male,19,NaN,NY,Current,Private,Asthma,NaN,96.4,124,79,84,2023-05-04
472,PT100472,Wei,Rodriguez,Female,77,O+,MA,Former,Private,GERD,NaN,91.6,118,54,91,2024-07-15
503,PT100503,Linda,Gonzalez,Male,58,AB+,IL,Former,Private,Chronic Kidney Disease,NaN,72.0,158,80,75,2024-05-02
526,PT100526,Jessica,Williams,Male,58,A+,NC,Never,Medicaid,Depression,NaN,76.1,113,75,68,2023-05-18
546,PT100546,Sofia,Jones,Female,55,O+,WA,Never,Private,Obesity,NaN,60.8,138,87,64,2024-11-21
563,PT100563,Elizabeth,Perez,Male,6,O+,AZ,Never,Medicare,Coronary Artery Disease,NaN,87.6,109,86,52,2024-02-13
613,PT100613,Amara,Kim,Other,69,O+,MA,Current,Uninsured,Asthma,NaN,69.2,120,73,67,2025-09-16
640,PT100640,Omar,Lee,Male,37,O-,AZ,Never,Medicaid,Anxiety Disorder,NaN,82.6,134,90,71,2025-03-16
660,PT100660,Jessica,White,Female,23,O+,NJ,Never,Medicare,Hypothyroidism,NaN,37.9,147,60,97,2023-06-16
666,PT100666,Thomas,Rodriguez,Male,78,O+,NJ,Never,Private,Coronary Artery Disease,NaN,83.6,143,83,91,2025-04-19
670,PT100670,Ingrid,Johnson,Female,40,B+,NJ,Never,Private,Chronic Kidney Disease,NaN,78.8,95,70,74,2024-06-19
688,PT100688,Joseph,Mueller,Male,21,A+,GA,Former,Private,Anxiety Disorder,NaN,90.4,119,97,58,2024-02-01
694,PT100694,Joseph,Kowalski,Male,86,O+,IL,Former,Medicare,Obesity,NaN,66.4,148,62,69,2025-10-20
713,PT100713,Barbara,Martinez,Male,88,A+,IL,Former,Uninsured,Migraine,NaN,90.9,131,80,53,2023-06-06
717,PT100717,Sarah,Gonzalez,Female,61,A+,WA,Former,Medicare,Type 2 Diabetes,NaN,64.2,93,69,86,2023-09-20
752,PT100752,Richard,White,Female,18,O+,NC,Never,Private,Anxiety Disorder,NaN,79.0,159,89,73,2025-01-26
824,PT100824,Charles,Martin,Male,57,O+,CA,Former,Medicare,Asthma,NaN,108.9,105,99,63,2024-12-06
884,PT100884,Wei,Wilson,Female,39,A+,NY,Current,Uninsured,Type 2 Diabetes,NaN,45.3,139,94,90,2024-11-01
911,PT100911,Elena,Gonzalez,Male,38,A+,VA,Never,Medicare,Hypertension,NaN,89.2,124,71,60,2025-06-17
915,PT100915,Hiroshi,Jones,Male,80,A+,VA,Never,Uninsured,Hypertension,NaN,61.8,135,83,87,2024-07-16
924,PT100924,Barbara,Williams,Female,41,A+,AZ,Never,Medicare,COPD,NaN,93.0,130,82,66,2023-11-11
928,PT100928,Mary,Gonzalez,Male,37,B+,GA,Never,Uninsured,Hypertension,NaN,60.8,138,64,61,2025-12-21
939,PT100939,Ingrid,White,Female,82,O+,GA,Never,Medicaid,Obesity,NaN,77.6,127,67,82,2023-08-02
944,PT100944,Elena,Lee,Female,51,B+,VA,Never,Private,Obesity,NaN,76.3,122,101,90,2024-09-23
965,PT100965,Ingrid,Patel,Female,71,O-,OH,Never,Medicaid,Coronary Artery Disease,NaN,100.5,148,68,76,2025-05-09
979,PT100979,Omar,Hernandez,Female,37,A+,PA,Former,Medicare,Type 2 Diabetes,NaN,106.1,123,54,86,2023-04-03
989,PT100989,Ahmed,Thompson,Male,64,B+,FL,Current,Medicare,Osteoarthritis,NaN,75.4,142,112,70,2023-01-31
994,PT100994,David,Martinez,Male,32,O+,NJ,Never,Uninsured,Obesity,NaN,59.0,152,94,79,2023-06-05
1012,PT101012,Diego,Mueller,Female,21,O+,TX,Current,VA,Obesity,NaN,79.3,157,85,87,2024-09-03
1038,PT101038,Barbara,Martinez,Female,88,B+,OH,Never,Private,Type 2 Diabetes,NaN,97.6,108,101,52,2023-09-23
1041,PT101041,Yuki,Wilson,Male,2,B+,TX,Former,Private,Hypertension,NaN,84.3,143,85,81,2024-05-24
1057,PT101057,Sarah,Khan,Female,2,B+,MI,Current,Private,Migraine,NaN,78.5,142,85,70,2025-08-18
1068,PT101068,Sarah,Smith,Female,49,O-,CA,Current,Uninsured,Coronary Artery Disease,NaN,51.7,159,81,49,2023-04-14
1072,PT101072,Thomas,Jackson,Female,69,A+,NC,Never,Medicaid,Hypertension,NaN,123.5,125,99,70,2023-01-23
1096,PT101096,Mary,Lopez,Female,9,O-,NY,Former,VA,Type 2 Diabetes,NaN,64.6,112,69,69,2024-08-04
1130,PT101130,Noor,Williams,Other,36,O+,IL,Former,Medicaid,Obesity,NaN,60.6,118,78,78,2023-09-02
1162,PT101162,Yuki,Nguyen,Male,39,A+,FL,Current,Private,Depression,NaN,66.9,102,91,70,2023-05-28

In [25]:
P_record['smoking_status'].unique()

<StringArray>
['Former', 'Never', nan, 'Current']
Length: 4, dtype: str

In [30]:
P_record[(P_record['smoking_status'].isna()) | (P_record['smoking_status'].isin(['NaN']))]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.1,74.0,124,62,70,2025-03-16
23,PT100023,Amara,Rodriguez,Male,78,O+,VA,NaN,Private,Type 2 Diabetes,173.3,86.9,120,79,70,2025-04-28
32,PT100032,Omar,Martinez,Female,15,B-,AZ,NaN,Medicaid,Hypertension,165.2,74.9,102,81,77,2024-01-01
52,PT100052,Kwame,Rossi,Male,9,AB-,VA,NaN,Private,Obesity,162.2,83.1,126,101,73,2025-10-08
116,PT100116,David,Moore,Male,65,O+,AZ,NaN,Uninsured,Hypothyroidism,178.0,77.6,118,74,66,2024-04-19
163,PT100163,Mary,Silva,Female,38,A+,CA,NaN,VA,Depression,176.6,87.3,144,104,90,2023-01-01
198,PT100198,Susan,Jackson,Female,92,O+,PA,NaN,Private,Type 2 Diabetes,158.0,73.7,143,89,80,2024-08-28
202,PT100202,Elena,Martinez,Male,74,O-,VA,NaN,Private,Type 2 Diabetes,163.5,68.4,114,97,81,2024-11-26
227,PT100227,Yuki,Lee,Male,0,B+,MI,NaN,Private,Depression,NaN,45.6,110,72,79,2023-12-25
228,PT100228,Karen,Johnson,Male,58,O+,IL,NaN,Private,Migraine,161.7,82.4,127,82,80,2024-01-26
245,PT100245,Amara,Wilson,Male,0,A+,PA,NaN,Private,Type 2 Diabetes,185.6,62.0,147,75,70,2024-04-15
253,PT100253,David,Johnson,Female,35,O+,MA,NaN,Medicare,Depression,NaN,74.2,150,77,59,2023-12-02
273,PT100273,Yuki,Smith,Male,17,NaN,MI,NaN,Private,Chronic Kidney Disease,178.5,52.1,97,99,86,2023-11-23
299,PT100299,Hiroshi,Thompson,Male,11,A+,CA,NaN,Medicaid,Atrial Fibrillation,152.3,68.8,134,70,86,2024-05-12
320,PT100320,Jennifer,Mueller,Male,59,A+,NC,NaN,Private,Coronary Artery Disease,173.4,72.4,131,65,82,2023-10-11
343,PT100343,Joseph,Martin,Male,89,O+,WA,NaN,Private,Asthma,174.4,88.4,135,59,83,2023-01-21
368,PT100368,Carlos,Martin,Female,45,A-,GA,NaN,Medicare,Type 2 Diabetes,161.8,91.4,125,89,69,2025-03-20
451,PT100451,Patricia,Jackson,Male,37,O+,TX,NaN,Medicaid,Hypertension,174.1,102.4,160,86,57,2024-10-27
466,PT100466,Sofia,Patel,Male,29,O+,MI,NaN,Medicaid,Atrial Fibrillation,167.4,89.8,126,89,95,2023-06-14
480,PT100480,Yuki,White,Female,3,B+,PA,NaN,Uninsured,Chronic Kidney Disease,167.3,NaN,121,80,100,2023-07-04
491,PT100491,Patricia,Williams,Male,54,O+,MI,NaN,Private,Atrial Fibrillation,154.5,79.9,124,99,63,2023-09-07
500,PT100500,Michael,Lopez,Male,48,O-,NC,NaN,VA,Depression,161.1,81.8,151,81,92,2025-12-14
514,PT100514,Sofia,Garcia,Female,38,A-,MI,NaN,Medicare,Type 2 Diabetes,161.7,85.7,134,99,63,2025-05-20
520,PT100520,Patricia,Hernandez,Male,30,A+,NC,NaN,Private,Hypertension,168.7,66.3,123,68,93,2025-03-23
521,PT100521,Ingrid,Davis,Female,73,A+,GA,NaN,Medicare,Obesity,160.0,82.9,99,77,82,2024-04-03
535,PT100535,Sofia,Johnson,Female,21,O+,TX,NaN,Medicaid,Depression,184.8,85.7,79,74,71,2025-09-03
570,PT100570,Michael,Kim,Female,58,B-,NY,NaN,Medicare,Coronary Artery Disease,164.4,65.9,142,72,72,2025-06-30
572,PT100572,Kwame,Silva,Female,56,A-,PA,NaN,Private,Type 2 Diabetes,197.6,63.5,115,84,81,2025-04-10
596,PT100596,Elena,Khan,Male,28,A+,NC,NaN,Private,Obesity,170.6,61.5,94,76,85,2024-12-31
600,PT100600,Sofia,Wilson,Female,73,O+,CA,NaN,Private,COPD,164.9,46.7,114,84,71,2024-01-14
625,PT100625,Yuki,Perez,Female,59,NaN,NY,NaN,Private,Obesity,158.0,85.9,124,75,72,2025-12-12
678,PT100678,Priya,Khan,Female,19,B+,FL,NaN,Private,Type 2 Diabetes,160.5,104.4,129,66,82,2023-07-04
685,PT100685,Ingrid,Jackson,Female,34,B+,MI,NaN,Medicaid,Osteoarthritis,165.3,43.5,153,97,81,2025-05-12
761,PT100761,Amara,Mueller,Female,84,O+,FL,NaN,Private,Type 2 Diabetes,179.4,NaN,135,99,74,2025-12-26
767,PT100767,Elena,Chen,Female,25,A+,VA,NaN,Private,Chronic Kidney Disease,166.6,92.4,117,74,87,2025-08-06
785,PT100785,Barbara,Silva,Female,90,B+,WA,NaN,Private,Asthma,174.7,89.9,110,68,101,2023-05-26
801,PT100801,Jennifer,Kim,Female,86,O+,MA,NaN,Medicare,Hypertension,160.9,NaN,105,94,68,2024-03-29
804,PT100804,Patricia,Moore,Female,28,A+,NY,NaN,Private,Depression,163.9,104.8,117,72,82,2025-01-20
807,PT100807,Charles,Moore,Female,77,A+,NC,NaN,Medicare,Anxiety Disorder,163.6,60.1,140,71,77,2024-09-09
835,PT100835,Linda,Smith,Male,54,B+,NJ,NaN,Private,Chronic Kidney Disease,177.4,65.6,140,72,49,2023-08-10
869,PT100869,Priya,Garcia,Female,93,B-,CA,NaN,Medicare,Hypothyroidism,180.4,80.6,120,86,77,2024-08-24
889,PT100889,Linda,Mueller,Male,17,O+,NJ,NaN,Private,Osteoarthritis,181.7,56.2,154,89,89,2024-05-21
894,PT100894,Sarah,Hernandez,Male,18,O+,PA,NaN,VA,Anxiety Disorder,160.4,70.7,117,79,85,2025-08-16
942,PT100942,John,Chen,Female,9,A+,FL,NaN,Private,Type 2 Diabetes,155.8,62.5,129,91,91,2024-09-02
956,PT100956,Thomas,Wilson,Male,5,O+,FL,NaN,Private,Type 2 Diabetes,151.6,75.7,124,94,85,2023-01-23
973,PT100973,David,Kim,Male,47,A+,GA,NaN,Private,Anxiety Disorder,179.0,101.0,116,82,71,2023-10-13
995,PT100995,Thomas,Lopez,Female,75,O+,WA,NaN,VA,Obesity,169.6,104.4,136,87,65,2025-07-09
1014,PT101014,David,Rossi,Female,56,A+,MI,NaN,Private,Atrial Fibrillation,171.5,78.5,120,77,84,2023-05-30
1019,PT101019,Priya,Jones,Female,26,O-,MI,NaN,Private,Hypothyroidism,151.5,80.0,108,90,69,2023-05-27
1127,PT101127,Yuki,Patel,Male,8,O+,IL,NaN,Uninsured,Migraine,170.6,NaN,122,55,45,2023-12-06
1161,PT101161,Sofia,Rodriguez,Male,16,O-,VA,NaN,Private,Coronary Artery Disease,178.4,92.2,120,106,67,2024-07-02
1169,PT101169,Thomas,Williams,Female,23,A+,PA,NaN,Private,COPD,150.4,89.9,119,77,79,2024-12-31

In [40]:
P_record['height_cm'].unique()

array([152.3, 183.2, 178.1, 171.5, 169.7, 181.8, 180.1, 179.6, 172.6,
       164.5,   nan, 176.2, 166.1, 179.3, 184.6, 160.5, 165.4, 172.9,
       162.8, 186.8, 172.2, 173.3, 185.6, 163.5, 167.1, 155.5, 166.3,
       153.1, 175.5, 165.2, 167. , 175.6, 156.6, 170. , 175. , 150.2,
       174.8, 151.3, 166.8, 156.4, 182.3, 151.5, 169.3, 163.9, 153. ,
       148.1, 157.6, 162.2, 176. , 181. , 179. , 166.5, 143.7, 171.9,
       182.7, 180.3, 156.1, 162.7, 187.3, 153.8, 156.5, 177.4, 163.7,
       156.2, 183.3, 164.2, 167.8, 182. , 176.9, 162.9, 182.5, 182.6,
       149.2, 173.5, 157.7, 170.6, 154.5, 163.3, 160. , 163. , 167.3,
       157.8, 183.7, 185.9, 166.4, 162.5, 166.2, 175.2, 155.6, 175.1,
       173.8, 180.7, 166.9, 159.4, 189.1, 152.7, 153.7, 173.7, 184.2,
       169.9, 178. , 148. , 149.3, 175.8, 152.5, 155.2, 173.1, 178.6,
       173.4, 165.8, 157.1, 173.6, 174.1, 171.1, 156.3, 174.9, 168. ,
       163.2, 165.1, 161.1, 158.1, 164.7, 184.1, 178.5, 151.6, 181.5,
       142.8, 179.2, 183.9, 159.3, 185.5, 145.7, 164.3, 163.8, 179.5,
       177.5, 176.6, 147.3, 178.4, 155.1, 165.9, 171.6, 167.2, 164.6,
       165. , 156.7, 171.2, 154.7, 156.8, 184.5, 168.6, 170.1, 147.9,
       162. , 146.5, 171.7, 180.8, 161.4, 145.6, 158. , 157. , 175.4,
       140.8, 177. , 152. , 182.4, 169. , 179.9, 195.3, 172.8, 161.7,
       142.7, 151.2, 183.5, 174.6, 166. , 164. , 162.3, 189.3, 172.4,
       157.3, 160.8, 172. , 168.5, 192.1, 179.8, 153.6, 181.7, 162.4,
       176.5, 202.4, 160.6, 155. , 158.6, 172.7, 172.5, 163.4, 187.8,
       172.3, 158.9, 141.5, 163.1, 161.2, 165.3, 186.7, 164.1, 171.4,
       162.1, 151. , 155.9, 169.8, 178.8, 150.1, 154.3, 167.5, 160.4,
       169.6, 159.7, 173.2, 176.3, 177.3, 154.8, 136. , 159.8, 148.3,
       161.5, 172.1, 167.7, 174. , 168.9, 159.9, 174.4, 157.9, 149.5,
       177.6, 168.8, 170.5, 157.2, 169.1, 184.8, 161.8, 160.7, 179.1,
       159.2, 177.2, 157.4, 166.6, 191.6, 170.3, 167.4, 160.3, 159.1,
       176.8, 162.6, 168.1, 149.4, 154.1, 184.4, 158.4, 164.9, 186. ,
       135.4, 163.6, 180. , 188.9, 169.5, 158.8, 165.7, 155.8, 169.2,
       187.7, 145.9, 200.3, 180.2, 174.3, 174.7, 158.7, 155.4, 176.1,
       151.9, 168.4, 153.9, 191.5, 152.6, 147.7, 167.6, 159.6, 164.8,
       151.1, 155.3, 182.1, 166.7, 168.7, 165.6, 175.3, 144. , 189.7,
       176.7, 148.6, 171. , 161.9, 164.4, 197.6, 181.4, 170.7, 194.8,
       193.7, 159.5, 149.9, 152.8, 188.4, 188.2, 167.9, 158.3, 158.2,
       160.2, 177.9, 181.1, 188.8, 180.5, 184.3, 185.4, 186.4, 174.5,
       161.3, 158.5, 149.7, 165.5, 186.5, 178.7, 147.8, 139.7, 154.4,
       178.3, 179.4, 195. , 173.9, 141.8, 147.1, 183.4, 160.9, 150.9,
       176.4, 177.8, 187.5, 174.2, 154.2, 156.9, 190.5, 144.7, 180.4,
       197. , 168.2, 147.6, 185.2, 161. , 150.3, 147.5, 150.4, 196.3,
       177.7, 186.1, 156. , 155.7, 137.2, 142.6, 170.4, 149.8, 154.6,
       153.3, 198.6, 154. , 150.8, 181.2, 173. , 149.1, 148.2, 160.1,
       147.4, 159. , 183.1, 188.6, 161.6, 152.4, 157.5, 170.8, 187.6,
       153.5, 187.9, 175.9, 153.4, 146.7, 179.7, 178.2, 140.3, 185.3,
       192.6, 180.6, 146.6, 177.1])

In [11]:
P_record['blood_type'].unique()

<StringArray>
['O+', 'A+', 'B+', 'AB+', 'O-', 'B-', nan, 'A-', 'AB-']
Length: 9, dtype: str

In [45]:
num_cols = P_record.select_dtypes(include='number').columns
P_record[num_cols]=P_record[num_cols].fillna(P_record[num_cols].median())
P_record[num_cols]

      age  height_cm  weight_kg  systolic_bp  diastolic_bp  heart_rate_bpm
0       0      152.3       81.8           71            58              75
1      53      183.2       45.6          114            89              75
2      70      178.1       66.5          104            71              66
3      52      171.5       74.8          147            77              99
4      36      169.7       65.0          117            59              72
...   ...        ...        ...          ...           ...             ...
1195   27      177.1       73.5          136            62              87
1196   32      175.9       83.8          146            73             102
1197   52      171.0       66.0          132            94              66
1198   27      175.2       74.8          157            71              94
1199   59      181.7       81.9          112            70              94

[1200 rows x 6 columns]

In [49]:
cat_cols = P_record.select_dtypes(include='object').columns
P_record[cat_cols]=P_record[cat_cols].fillna('unknown')
P_record[cat_cols]

C:\Users\lands\AppData\Local\Temp\ipykernel_1252\2074161501.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = P_record.select_dtypes(include='object').columns

,patient_id,first_name,last_name,gender,blood_type,state,smoking_status,insurance_type,primary_condition,last_admission_date
0,PT100000,Sarah,Jackson,Male,O+,CA,Former,Private,Type 2 Diabetes,2024-07-19
1,PT100001,Jessica,Smith,Female,O+,PA,Former,Medicaid,Anxiety Disorder,2025-01-16
2,PT100002,John,Nguyen,Male,A+,PA,Never,Private,Asthma,2023-10-11
3,PT100003,Robert,Brown,Male,O+,PA,Former,Medicare,Chronic Kidney Disease,2023-08-09
4,PT100004,Priya,Rossi,Female,O+,AZ,Never,Medicaid,Type 2 Diabetes,2024-11-15
...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,unknown,AZ,Never,Private,Atrial Fibrillation,2025-06-12
1196,PT101196,Joseph,Rodriguez,Female,O+,NY,Never,Private,Osteoarthritis,2023-03-11
1197,PT101197,Patricia,White,Male,A+,PA,Current,Private,Chronic Kidney Disease,2025-08-01
1198,PT101198,John,Chen,Female,O-,CA,Never,Medicare,GERD,2024-01-27
1199,PT101199,Susan,Thompson,Male,A+,IL,Never,Private,Depression,2025-06-15

In [50]:
P_record['blood_type'].unique()

<StringArray>
['O+', 'A+', 'B+', 'AB+', 'O-', 'B-', 'unknown', 'A-', 'AB-']
Length: 9, dtype: str

In [29]:
P_record[(P_record['blood_type'].isna()) | (P_record['blood_type'].isin(['NaN']))]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
31,PT100031,John,Jones,Male,49,NaN,CA,Never,Private,Depression,172.2,81.7,147,85,80,2024-05-28
63,PT100063,Jessica,Johnson,Male,55,NaN,FL,Current,Medicaid,COPD,162.7,74.8,145,104,86,2024-04-29
79,PT100079,Joseph,Gonzalez,Male,12,NaN,WA,Never,Medicaid,Atrial Fibrillation,162.9,112.7,139,88,62,2023-06-20
110,PT100110,Richard,Kowalski,Female,18,NaN,MI,Never,Medicare,GERD,189.1,60.5,139,91,58,2024-11-05
113,PT100113,Robert,Martin,Male,71,NaN,OH,Former,Medicaid,Hypothyroidism,173.7,47.5,77,87,63,2023-07-15
177,PT100177,Richard,Jackson,Other,42,NaN,NC,Never,Private,Migraine,165.0,71.6,124,81,89,2024-03-27
180,PT100180,Carlos,Martin,Male,36,NaN,TX,Current,Medicare,Coronary Artery Disease,171.2,73.9,113,83,87,2024-07-02
201,PT100201,Karen,Davis,Male,20,NaN,OH,Current,Medicaid,Hypothyroidism,140.8,118.1,100,90,79,2023-07-07
222,PT100222,Charles,Lee,Male,9,NaN,NC,Former,Medicare,Atrial Fibrillation,164.3,72.3,115,70,82,2024-12-30
264,PT100264,William,Chen,Male,20,NaN,OH,Never,Private,Atrial Fibrillation,172.5,84.2,147,87,80,2025-06-10
268,PT100268,Elizabeth,Thomas,Female,7,NaN,NC,Current,VA,Hypertension,166.8,87.8,135,69,82,2024-03-28
273,PT100273,Yuki,Smith,Male,17,NaN,MI,NaN,Private,Chronic Kidney Disease,178.5,52.1,97,99,86,2023-11-23
382,PT100382,Linda,Chen,Male,72,NaN,FL,Current,Medicaid,COPD,170.0,53.1,107,104,79,2024-10-31
414,PT100414,John,Williams,Female,18,NaN,VA,Never,Private,Type 2 Diabetes,163.3,68.5,114,70,75,2024-06-04
436,PT100436,Susan,Jones,Female,91,NaN,NJ,Never,Private,Atrial Fibrillation,155.8,62.7,120,58,105,2025-11-28
440,PT100440,Joseph,Gonzalez,Male,41,NaN,TX,Never,Private,Hypertension,172.3,91.7,113,58,84,2024-11-23
441,PT100441,Jessica,Perez,Female,66,NaN,CA,Never,Private,Migraine,169.2,75.0,119,88,71,2024-04-29
448,PT100448,Karen,Chen,Female,26,NaN,TX,Never,Private,Coronary Artery Disease,166.4,59.7,138,73,72,2025-10-11
458,PT100458,Thomas,Williams,Male,68,NaN,MA,Never,Medicare,Anxiety Disorder,181.0,86.5,99,84,51,2024-12-04
469,PT100469,Richard,Wilson,Male,19,NaN,NY,Current,Private,Asthma,NaN,96.4,124,79,84,2023-05-04
485,PT100485,Mary,White,Female,14,NaN,NJ,Former,Private,Type 2 Diabetes,179.0,69.8,124,69,71,2025-05-08
488,PT100488,Robert,Rodriguez,Male,14,NaN,NJ,Never,Medicaid,Asthma,151.1,66.3,110,100,50,2023-10-21
499,PT100499,Susan,Mueller,Male,19,NaN,GA,Current,Medicaid,Asthma,168.0,68.4,135,103,98,2023-07-20
522,PT100522,Jessica,Nguyen,Female,11,NaN,TX,Never,Private,Hypertension,157.8,83.0,167,88,89,2024-07-27
527,PT100527,Amara,Hernandez,Other,30,NaN,AZ,Never,Private,Obesity,162.3,79.8,159,94,74,2023-05-23
542,PT100542,John,Gonzalez,Male,72,NaN,MA,Current,Medicaid,Depression,169.5,102.6,114,80,68,2024-09-29
554,PT100554,Carlos,Silva,Female,26,NaN,OH,Never,Uninsured,COPD,163.3,71.6,92,72,77,2025-12-17
566,PT100566,Thomas,Brown,Male,22,NaN,TX,Current,Medicare,Hypertension,164.8,89.7,133,94,72,2025-03-29
611,PT100611,Patricia,Patel,Male,48,NaN,VA,Never,Medicare,COPD,176.8,56.9,106,82,67,2024-03-29
616,PT100616,John,Patel,Male,50,NaN,VA,Never,Private,Atrial Fibrillation,165.7,90.6,129,88,79,2025-04-30
625,PT100625,Yuki,Perez,Female,59,NaN,NY,NaN,Private,Obesity,158.0,85.9,124,75,72,2025-12-12
630,PT100630,James,Patel,Male,69,NaN,VA,Never,Medicare,Hypertension,159.7,65.7,116,70,56,2024-03-15
643,PT100643,Susan,Patel,Female,50,NaN,PA,Never,Private,Coronary Artery Disease,158.2,125.0,123,91,70,2023-03-12
652,PT100652,Ahmed,Lopez,Male,71,NaN,NC,Never,Medicaid,Hypertension,156.6,61.4,110,70,73,2025-04-23
663,PT100663,Yuki,White,Female,12,NaN,CA,Former,Medicaid,Osteoarthritis,180.5,70.8,129,76,62,2025-08-28
679,PT100679,Amara,Rodriguez,Female,42,NaN,IL,Never,Private,Osteoarthritis,151.5,92.7,119,91,80,2024-02-21
725,PT100725,Charles,Martin,Female,84,NaN,CA,Former,Private,Osteoarthritis,139.7,77.5,127,96,94,2025-03-26
750,PT100750,Fatima,Nguyen,Female,67,NaN,AZ,Never,Private,Obesity,160.3,71.4,139,65,85,2024-02-04
765,PT100765,Carlos,Martinez,Female,38,NaN,TX,Former,Private,Asthma,173.9,65.7,98,88,89,2024-05-24
780,PT100780,Joseph,Kowalski,Female,21,NaN,NY,Never,Uninsured,Obesity,177.2,85.3,129,92,57,2025-04-10
791,PT100791,Elena,Nguyen,Female,64,NaN,AZ,Never,Medicaid,Hypertension,157.2,83.0,152,73,61,2024-11-15
825,PT100825,Jessica,Smith,Female,73,NaN,NJ,Never,Medicare,Hypertension,187.5,58.1,123,93,89,2025-01-13
861,PT100861,Joseph,Smith,Male,45,NaN,GA,Never,Private,Type 2 Diabetes,184.2,113.4,127,66,67,2025-01-04
914,PT100914,Patricia,Silva,Other,38,NaN,MA,Never,Private,Hypertension,173.4,86.3,126,68,63,2024-12-25
932,PT100932,Richard,Silva,Female,23,NaN,VA,Never,Private,Coronary Artery Disease,147.5,69.7,132,83,73,2024-02-10
938,PT100938,Kwame,Smith,Male,81,NaN,MI,Never,Private,Anxiety Disorder,155.4,75.6,126,76,85,2023-08-24
959,PT100959,Richard,Mueller,Male,50,NaN,MA,Never,Private,Type 2 Diabetes,172.5,76.2,118,54,98,2023-11-04
967,PT100967,Hiroshi,Miller,Female,27,NaN,WA,Never,Medicaid,GERD,185.4,75.8,112,65,97,2025-11-16
975,PT100975,Carlos,Rodriguez,Male,48,NaN,NJ,Never,Private,Type 2 Diabetes,155.8,88.6,114,81,89,2023-06-23
1029,PT101029,Jennifer,Patel,Female,28,NaN,IL,Current,Private,Migraine,157.3,93.7,106,74,73,2023-10-17
1054,PT101054,Elizabeth,Patel,Female,77,NaN,PA,Former,Medicaid,Obesity,161.0,66.3,121,107,63,2025-03-09
1058,PT101058,David,Anderson,Male,79,NaN,PA,Never,Private,Type 2 Diabetes,157.8,92.8,114,83,84,2023-10-01
1088,PT101088,Carlos,Patel,Female,42,NaN,FL,Never,Private,Anxiety Disorder,159.0,80.5,149,70,70,2025-09-03
1188,PT101188,Omar,Gonzalez,Female,61,NaN,WA,Never,Private,Hypertension,167.8,97.7,140,73,81,2025-12-07
1195,PT101195,Elizabeth,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12

In [3]:
P_record.shape

(1200, 16)

In [4]:
P_record.dtypes

patient_id                 str
first_name                 str
last_name                  str
gender                     str
age                      int64
blood_type                 str
state                      str
smoking_status             str
insurance_type             str
primary_condition          str
height_cm              float64
weight_kg              float64
systolic_bp              int64
diastolic_bp             int64
heart_rate_bpm           int64
last_admission_date        str
dtype: object

In [5]:
P_record.index

RangeIndex(start=0, stop=1200, step=1)

In [6]:
P_record.columns

Index(['patient_id', 'first_name', 'last_name', 'gender', 'age', 'blood_type',
       'state', 'smoking_status', 'insurance_type', 'primary_condition',
       'height_cm', 'weight_kg', 'systolic_bp', 'diastolic_bp',
       'heart_rate_bpm', 'last_admission_date'],
      dtype='str')

In [7]:
P_record.values

array([['PT100000', 'Sarah', 'Jackson', ..., 58, 75, '2024-07-19'],
       ['PT100001', 'Jessica', 'Smith', ..., 89, 75, '2025-01-16'],
       ['PT100002', 'John', 'Nguyen', ..., 71, 66, '2023-10-11'],
       ...,
       ['PT101197', 'Patricia', 'White', ..., 94, 66, '2025-08-01'],
       ['PT101198', 'John', 'Chen', ..., 71, 94, '2024-01-27'],
       ['PT101199', 'Susan', 'Thompson', ..., 70, 94, '2025-06-15']],
      shape=(1200, 16), dtype=object)

In [9]:
P_record.head()

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15

In [10]:
P_record.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [11]:
P_record.tail()

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
1195,PT101195,Elizabeth,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12
1196,PT101196,Joseph,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
1197,PT101197,Patricia,White,Male,52,A+,PA,Current,Private,Chronic Kidney Disease,171.0,66.0,132,94,66,2025-08-01
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [12]:
P_record.tail(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [13]:
P_record.sample()

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
1020,PT101020,Elena,Kowalski,Male,49,A+,NY,Never,Private,Coronary Artery Disease,161.3,81.7,92,92,72,2025-02-26

In [14]:
P_record.sample(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
331,PT100331,Fatima,Perez,Female,49,O+,CA,Never,Private,Hypothyroidism,148.3,69.4,118,66,92,2023-09-28
232,PT100232,Thomas,Lee,Male,86,A-,WA,Never,Medicaid,Obesity,189.3,59.9,153,103,67,2024-11-10

In [15]:
P_record.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1200 non-null   str
 1   first_name           1200 non-null   str
 2   last_name            1200 non-null   str
 3   gender               1200 non-null   str
 4   age                  1200 non-null   int64
 5   blood_type           1145 non-null   str
 6   state                1200 non-null   str
 7   smoking_status       1148 non-null   str
 8   insurance_type       1200 non-null   str
 9   primary_condition    1195 non-null   str
 10  height_cm            1147 non-null   float64
 11  weight_kg            1152 non-null   float64
 12  systolic_bp          1200 non-null   int64
 13  diastolic_bp         1200 non-null   int64
 14  heart_rate_bpm       1200 non-null   int64
 15  last_admission_date  1200 non-null   str
dtypes: float64(2), int64(4), str(10)
memory usage: 150.1 KB

In [16]:
## numericl columns only----------->statistical overview

P_record.describe()

,age,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm
count,1200.000000,1147.000000,1152.000000,1200.000000,1200.000000,1200.000000
mean,47.073333,167.392153,75.081163,124.052500,79.783333,75.570000
std,27.469530,10.439979,15.978771,17.688098,12.054078,12.214449
min,0.000000,135.400000,25.100000,71.000000,44.000000,28.000000
25%,22.000000,160.400000,64.275000,112.000000,72.000000,67.000000
50%,45.500000,167.200000,74.800000,124.000000,79.000000,75.000000
75%,72.000000,174.400000,85.725000,135.000000,88.000000,84.000000
max,94.000000,202.400000,126.200000,200.000000,116.000000,112.000000

In [17]:
## all columns

P_record.describe(include='all')

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
count,1200,1200,1200,1200,1200.000000,1145,1200,1148,1200,1195,1147.000000,1152.000000,1200.000000,1200.000000,1200.000000,1200
unique,1200,35,33,3,NaN,8,15,3,5,14,NaN,NaN,NaN,NaN,NaN,740
top,PT100000,Elizabeth,Martin,Female,NaN,O+,PA,Never,Private,Hypertension,NaN,NaN,NaN,NaN,NaN,2024-12-08
freq,1,48,53,591,NaN,422,96,639,639,177,NaN,NaN,NaN,NaN,NaN,6
mean,NaN,NaN,NaN,NaN,47.073333,NaN,NaN,NaN,NaN,NaN,167.392153,75.081163,124.052500,79.783333,75.570000,NaN
std,NaN,NaN,NaN,NaN,27.469530,NaN,NaN,NaN,NaN,NaN,10.439979,15.978771,17.688098,12.054078,12.214449,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,135.400000,25.100000,71.000000,44.000000,28.000000,NaN
25%,NaN,NaN,NaN,NaN,22.000000,NaN,NaN,NaN,NaN,NaN,160.400000,64.275000,112.000000,72.000000,67.000000,NaN
50%,NaN,NaN,NaN,NaN,45.500000,NaN,NaN,NaN,NaN,NaN,167.200000,74.800000,124.000000,79.000000,75.000000,NaN
75%,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,174.400000,85.725000,135.000000,88.000000,84.000000,NaN
max,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,NaN,NaN,202.400000,126.200000,200.000000,116.000000,112.000000,NaN

In [20]:
## all columns
P_record.describe(include='object')

C:\Users\lands\AppData\Local\Temp\ipykernel_13952\2346955189.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  P_record.describe(include='object')

,patient_id,first_name,last_name,gender,blood_type,state,smoking_status,insurance_type,primary_condition,last_admission_date
count,1200,1200,1200,1200,1145,1200,1148,1200,1195,1200
unique,1200,35,33,3,8,15,3,5,14,740
top,PT100000,Elizabeth,Martin,Female,O+,PA,Never,Private,Hypertension,2024-12-08
freq,1,48,53,591,422,96,639,639,177,6

In [21]:
P_record.isnull()

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
P_record.isnull().sum()

patient_id              0
first_name              0
last_name               0
gender                  0
age                     0
blood_type             55
state                   0
smoking_status         52
insurance_type          0
primary_condition       5
height_cm              53
weight_kg              48
systolic_bp             0
diastolic_bp            0
heart_rate_bpm          0
last_admission_date     0
dtype: int64

In [23]:
P_record.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Length: 1200, dtype: bool

In [24]:
P_record.duplicated().sum()

np.int64(0)

In [32]:
P_record.rename(columns={'patient_id':'P_ID', 'first_name':'F_N', 'last_name':'L_N', 'gender':'Sex', 'blood_type':'B_G', 'insurance_type':'I_T', 'primary_condition':'P_C'}, inplace=True)
P_record

,P_ID,F_N,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12
1196,PT101196,Joseph,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
1197,PT101197,Patricia,White,Male,52,A+,PA,Current,Private,Chronic Kidney Disease,171.0,66.0,132,94,66,2025-08-01
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [33]:
P_record.sum(axis=0)

P_ID                   PT100000PT100001PT100002PT100003PT100004PT1000...
F_N                    SarahJessicaJohnRobertPriyaKarenKarenJenniferS...
L_N                    JacksonSmithNguyenBrownRossiRodriguezGonzalezG...
Sex                    MaleFemaleMaleMaleFemaleMaleMaleMaleFemaleFema...
age                                                                56488
B_G                    O+O+A+O+O+O+A+B+B+A+A+B+O+A+O+O+O+AB+AB+O+O-AB...
state                  CAPAPAPAAZNYNCMAAZMIMAOHMINCNYNYAZTXPAMINCGAMA...
smoking_status         FormerFormerNeverFormerNeverFormerNeverNeverFo...
I_T                    PrivateMedicaidPrivateMedicareMedicaidMedicaid...
P_C                    Type 2 DiabetesAnxiety DisorderAsthmaChronic K...
height_cm                                                       191998.8
weight_kg                                                        86493.5
systolic_bp                                                       148863
diastolic_bp                                                       95740
heart_rate_bpm                                                     90684
last_admission_date    2024-07-192025-01-162023-10-112023-08-092024-1...
dtype: object

In [35]:
P_record['F_N']

0           Sarah
1         Jessica
2            John
3          Robert
4           Priya
          ...
1195    Elizabeth
1196       Joseph
1197     Patricia
1198         John
1199        Susan
Name: F_N, Length: 1200, dtype: str

In [36]:
type(P_record['F_N'])

pandas.Series

In [40]:
P_record[['F_N', 'L_N', 'I_T']]

            F_N        L_N       I_T
0         Sarah    Jackson   Private
1       Jessica      Smith  Medicaid
2          John     Nguyen   Private
3        Robert      Brown  Medicare
4         Priya      Rossi  Medicaid
...         ...        ...       ...
1195  Elizabeth      Silva   Private
1196     Joseph  Rodriguez   Private
1197   Patricia      White   Private
1198       John       Chen  Medicare
1199      Susan   Thompson   Private

[1200 rows x 3 columns]

In [41]:
type(P_record[['F_N', 'L_N', 'I_T']])

pandas.DataFrame

In [42]:
P_record.iloc[0]

P_ID                          PT100000
F_N                              Sarah
L_N                            Jackson
Sex                               Male
age                                  0
B_G                                 O+
state                               CA
smoking_status                  Former
I_T                            Private
P_C                    Type 2 Diabetes
height_cm                        152.3
weight_kg                         81.8
systolic_bp                         71
diastolic_bp                        58
heart_rate_bpm                      75
last_admission_date         2024-07-19
Name: 0, dtype: object

In [43]:
P_record.iloc[1]

P_ID                           PT100001
F_N                             Jessica
L_N                               Smith
Sex                              Female
age                                  53
B_G                                  O+
state                                PA
smoking_status                   Former
I_T                            Medicaid
P_C                    Anxiety Disorder
height_cm                         183.2
weight_kg                          45.6
systolic_bp                         114
diastolic_bp                         89
heart_rate_bpm                       75
last_admission_date          2025-01-16
Name: 1, dtype: object

In [44]:
P_record.iloc[0:10:2]

,P_ID,F_N,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.1,74.0,124,62,70,2025-03-16
8,PT100008,Sarah,Nguyen,Female,44,B+,AZ,Never,Private,Atrial Fibrillation,172.6,93.0,118,75,90,2023-05-13

In [46]:
P_record.loc[2]

P_ID                     PT100002
F_N                          John
L_N                        Nguyen
Sex                          Male
age                            70
B_G                            A+
state                          PA
smoking_status              Never
I_T                       Private
P_C                        Asthma
height_cm                   178.1
weight_kg                    66.5
systolic_bp                   104
diastolic_bp                   71
heart_rate_bpm                 66
last_admission_date    2023-10-11
Name: 2, dtype: object

In [52]:
P_record.set_index(['F_N'], inplace=True)
P_record

,P_ID,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
F_N,,,,,,,,,,,,,,,
Sarah,PT100000,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
Jessica,PT100001,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
John,PT100002,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
Robert,PT100003,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
Priya,PT100004,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Elizabeth,PT101195,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12
Joseph,PT101196,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
Patricia,PT101197,White,Male,52,A+,PA,Current,Private,Chronic Kidney Disease,171.0,66.0,132,94,66,2025-08-01
John,PT101198,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
Susan,PT101199,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [55]:
P_record.loc['Priya']

,P_ID,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
F_N,,,,,,,,,,,,,,,
Priya,PT100004,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
Priya,PT100094,Martinez,Female,39,A-,NY,Never,Medicaid,Coronary Artery Disease,172.9,66.0,122,66,73,2024-03-17
Priya,PT100138,Silva,Male,50,A+,NJ,Former,Medicare,Type 2 Diabetes,165.1,94.7,126,85,88,2025-01-05
Priya,PT100165,Martin,Female,40,A+,TX,Former,Private,Osteoarthritis,151.3,91.5,137,93,28,2024-01-19
Priya,PT100354,Johnson,Female,94,O+,MA,Never,Private,Obesity,178.8,72.1,135,76,59,2024-10-15
Priya,PT100427,Brown,Male,89,A+,NC,Current,Private,Type 2 Diabetes,NaN,69.8,130,72,74,2024-12-14
Priya,PT100510,Smith,Female,10,O-,IL,Current,Medicaid,Hypothyroidism,166.9,83.0,114,76,62,2025-11-17
Priya,PT100545,Anderson,Female,10,A+,PA,Never,Private,COPD,148.6,97.9,170,78,75,2024-02-01
Priya,PT100649,Lopez,Female,67,O+,TX,Current,Medicaid,Anxiety Disorder,170.1,NaN,120,107,67,2025-05-26
Priya,PT100655,Kowalski,Female,45,O+,VA,Never,Uninsured,Hypertension,173.3,97.1,117,71,80,2023-12-20
Priya,PT100678,Khan,Female,19,B+,FL,NaN,Private,Type 2 Diabetes,160.5,104.4,129,66,82,2023-07-04
Priya,PT100862,Martin,Male,70,B+,NC,Former,Private,NaN,175.4,73.8,172,72,77,2025-08-25
Priya,PT100866,Thomas,Male,70,O-,MI,Former,Medicare,Chronic Kidney Disease,163.4,NaN,142,89,74,2024-01-02
Priya,PT100869,Garcia,Female,93,B-,CA,NaN,Medicare,Hypothyroidism,180.4,80.6,120,86,77,2024-08-24
Priya,PT100879,Kowalski,Male,69,A-,PA,Never,Medicaid,Depression,179.0,45.1,164,81,98,2023-08-06
Priya,PT100948,Rodriguez,Male,11,AB+,PA,Current,Uninsured,Anxiety Disorder,163.1,82.9,121,88,98,2023-03-26
Priya,PT100986,Taylor,Female,73,O+,MA,Never,Private,Obesity,156.5,94.2,115,90,79,2024-08-09
Priya,PT100999,Smith,Female,68,O+,NC,Never,Medicare,Coronary Artery Disease,173.8,59.3,102,70,97,2023-03-08
Priya,PT101005,Jackson,Female,33,A+,NC,Never,Private,Obesity,166.0,83.4,121,67,66,2023-06-01
Priya,PT101017,Lopez,Male,83,O+,PA,Never,Private,Anxiety Disorder,176.9,67.7,122,85,87,2023-11-16
Priya,PT101019,Jones,Female,26,O-,MI,NaN,Private,Hypothyroidism,151.5,80.0,108,90,69,2023-05-27
Priya,PT101075,Davis,Female,20,A+,OH,Never,Medicaid,Asthma,169.2,81.5,131,88,76,2024-03-07
Priya,PT101116,Anderson,Female,16,A+,IL,Former,Private,COPD,167.4,85.0,103,71,83,2024-04-06
Priya,PT101128,Smith,Male,17,B+,GA,Former,Private,Coronary Artery Disease,162.9,66.9,108,90,87,2025-11-27
Priya,PT101133,White,Male,94,O+,NJ,Never,Private,Migraine,173.7,63.4,137,99,77,2025-04-26

In [62]:
P_record.head()

,P_ID,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
F_N,,,,,,,,,,,,,,,
Sarah,PT100000,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
Jessica,PT100001,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
John,PT100002,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
Robert,PT100003,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
Priya,PT100004,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15

In [65]:
### important

P_record[(P_record.index=='Priya')  & (P_record['L_N']=='Rossi')]

,P_ID,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
F_N,,,,,,,,,,,,,,,
Priya,PT100004,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15

In [63]:
print(repr(P_record.columns.tolist()))

['P_ID', 'L_N', 'Sex', 'age', 'B_G', 'state', 'smoking_status', 'I_T', 'P_C', 'height_cm', 'weight_kg', 'systolic_bp', 'diastolic_bp', 'heart_rate_bpm', 'last_admission_date']

In [66]:
P_record[(P_record.index=='Priya')].shape

(25, 15)

In [4]:
### Which columns in the patient records dataset have missing values, and how many are missing in each? What would be a 
## reasonable way to handle them (drop, fill with mean/median, or flag as "unknown")?

P_record.isna().sum()

patient_id              0
first_name              0
last_name               0
gender                  0
age                     0
blood_type             55
state                   0
smoking_status         52
insurance_type          0
primary_condition       5
height_cm              53
weight_kg              48
systolic_bp             0
diastolic_bp            0
heart_rate_bpm          0
last_admission_date     0
dtype: int64

In [137]:
P_record['height_cm'].isna().sum()

np.int64(0)

In [139]:
P_record['height_cm'].unique()

array([167.39215344])

In [149]:
P_record=pd.read_csv('E:\\code\\patient_records.csv')
P_record

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12
1196,PT101196,Joseph,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
1197,PT101197,Patricia,White,Male,52,A+,PA,Current,Private,Chronic Kidney Disease,171.0,66.0,132,94,66,2025-08-01
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [82]:
import numpy as np
P_record.replace('',np.nan, inplace=True)
P_record.replace('NaN',np.nan, inplace=True)
P_record.head()

,P_ID,L_N,Sex,age,B_G,state,smoking_status,I_T,P_C,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
F_N,,,,,,,,,,,,,,,
Sarah,PT100000,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
Jessica,PT100001,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
John,PT100002,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
Robert,PT100003,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
Priya,PT100004,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15

In [150]:
print(P_record['height_cm'].value_counts().head(10))

height_cm
174.4    10
172.6     9
168.0     9
165.4     8
173.3     8
173.7     8
169.0     8
172.7     8
172.2     7
166.3     7
Name: count, dtype: int64

In [153]:
P_record['height_cm']=P_record['height_cm'].fillna(P_record['height_cm'].mean())
P_record.head(25)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.300000,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.200000,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.100000,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.500000,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.700000,65.0,117,59,72,2024-11-15
5,PT100005,Karen,Rodriguez,Male,78,O+,NY,Former,Medicaid,Depression,181.800000,100.9,115,69,76,2024-02-25
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.100000,74.0,124,62,70,2025-03-16
7,PT100007,Jennifer,Garcia,Male,67,B+,MA,Never,Private,Asthma,179.600000,76.4,114,75,80,2023-06-10
8,PT100008,Sarah,Nguyen,Female,44,B+,AZ,Never,Private,Atrial Fibrillation,172.600000,93.0,118,75,90,2023-05-13
9,PT100009,John,Kim,Female,2,A+,MI,Former,Private,Hypertension,164.500000,72.1,127,81,95,2024-08-28
10,PT100010,Jennifer,Williams,Female,50,A+,MA,Never,Medicare,Hypertension,167.392153,77.8,117,95,66,2024-03-05
11,PT100011,Sarah,Brown,Male,4,B+,OH,Current,Private,Obesity,176.200000,89.4,117,88,88,2025-03-09
12,PT100012,Wei,Lee,Male,88,O+,MI,Former,Private,Depression,166.100000,51.4,107,61,82,2024-07-08
13,PT100013,Fatima,Khan,Male,57,A+,NC,Former,Private,Type 2 Diabetes,164.500000,70.4,104,87,87,2024-01-24
14,PT100014,Omar,Brown,Female,35,O+,NY,Never,Medicare,Obesity,179.300000,88.3,126,81,74,2023-06-24
15,PT100015,Ahmed,Davis,Female,46,O+,NY,Former,Private,Asthma,184.600000,76.0,131,79,73,2023-06-28
16,PT100016,Susan,Moore,Male,58,O+,AZ,Current,Medicare,Obesity,160.500000,98.5,99,80,86,2025-04-07
17,PT100017,Kwame,Brown,Female,24,AB+,TX,Never,Private,Depression,165.400000,49.8,139,82,86,2023-09-06
18,PT100018,Patricia,Hernandez,Male,27,AB+,PA,Never,VA,GERD,171.500000,48.0,139,72,94,2024-07-04
19,PT100019,Ingrid,Smith,Male,39,O+,MI,Never,Medicare,Chronic Kidney Disease,172.900000,87.3,143,78,77,2025-06-14
20,PT100020,Susan,Taylor,Male,24,O-,NC,Never,Private,Depression,162.800000,88.9,130,94,74,2025-09-10
21,PT100021,Elena,White,Female,72,AB+,GA,Former,Private,Obesity,186.800000,71.9,136,72,45,2023-10-21
22,PT100022,Yuki,Wilson,Male,9,O+,MA,Never,Private,Asthma,172.200000,NaN,164,68,56,2023-05-01
23,PT100023,Amara,Rodriguez,Male,78,O+,VA,NaN,Private,Type 2 Diabetes,173.300000,86.9,120,79,70,2025-04-28
24,PT100024,Noor,Anderson,Male,33,O+,MA,Never,Private,GERD,185.600000,62.0,106,66,62,2025-01-22

In [155]:
P_record['height_cm'].ffill().head(20)

0     152.300000
1     183.200000
2     178.100000
3     171.500000
4     169.700000
5     181.800000
6     180.100000
7     179.600000
8     172.600000
9     164.500000
10    167.392153
11    176.200000
12    166.100000
13    164.500000
14    179.300000
15    184.600000
16    160.500000
17    165.400000
18    171.500000
19    172.900000
Name: height_cm, dtype: float64

In [156]:
P_record['weight_kg'].ffill().head(20)

0      81.8
1      45.6
2      66.5
3      66.5
4      65.0
5     100.9
6      74.0
7      76.4
8      93.0
9      72.1
10     77.8
11     89.4
12     51.4
13     70.4
14     88.3
15     76.0
16     98.5
17     49.8
18     48.0
19     87.3
Name: weight_kg, dtype: float64

In [164]:
P_record['weight_kg'].bfill(inplace=True)
P_record.head(25)

C:\Users\lands\AppData\Local\Temp\ipykernel_13952\1422941223.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  P_record['weight_kg'].bfill(inplace=True)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.300000,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.200000,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.100000,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.500000,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.700000,65.0,117,59,72,2024-11-15
5,PT100005,Karen,Rodriguez,Male,78,O+,NY,Former,Medicaid,Depression,181.800000,100.9,115,69,76,2024-02-25
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.100000,74.0,124,62,70,2025-03-16
7,PT100007,Jennifer,Garcia,Male,67,B+,MA,Never,Private,Asthma,179.600000,76.4,114,75,80,2023-06-10
8,PT100008,Sarah,Nguyen,Female,44,B+,AZ,Never,Private,Atrial Fibrillation,172.600000,93.0,118,75,90,2023-05-13
9,PT100009,John,Kim,Female,2,A+,MI,Former,Private,Hypertension,164.500000,72.1,127,81,95,2024-08-28
10,PT100010,Jennifer,Williams,Female,50,A+,MA,Never,Medicare,Hypertension,167.392153,77.8,117,95,66,2024-03-05
11,PT100011,Sarah,Brown,Male,4,B+,OH,Current,Private,Obesity,176.200000,89.4,117,88,88,2025-03-09
12,PT100012,Wei,Lee,Male,88,O+,MI,Former,Private,Depression,166.100000,51.4,107,61,82,2024-07-08
13,PT100013,Fatima,Khan,Male,57,A+,NC,Former,Private,Type 2 Diabetes,164.500000,70.4,104,87,87,2024-01-24
14,PT100014,Omar,Brown,Female,35,O+,NY,Never,Medicare,Obesity,179.300000,88.3,126,81,74,2023-06-24
15,PT100015,Ahmed,Davis,Female,46,O+,NY,Former,Private,Asthma,184.600000,76.0,131,79,73,2023-06-28
16,PT100016,Susan,Moore,Male,58,O+,AZ,Current,Medicare,Obesity,160.500000,98.5,99,80,86,2025-04-07
17,PT100017,Kwame,Brown,Female,24,AB+,TX,Never,Private,Depression,165.400000,49.8,139,82,86,2023-09-06
18,PT100018,Patricia,Hernandez,Male,27,AB+,PA,Never,VA,GERD,171.500000,48.0,139,72,94,2024-07-04
19,PT100019,Ingrid,Smith,Male,39,O+,MI,Never,Medicare,Chronic Kidney Disease,172.900000,87.3,143,78,77,2025-06-14
20,PT100020,Susan,Taylor,Male,24,O-,NC,Never,Private,Depression,162.800000,88.9,130,94,74,2025-09-10
21,PT100021,Elena,White,Female,72,AB+,GA,Former,Private,Obesity,186.800000,71.9,136,72,45,2023-10-21
22,PT100022,Yuki,Wilson,Male,9,O+,MA,Never,Private,Asthma,172.200000,NaN,164,68,56,2023-05-01
23,PT100023,Amara,Rodriguez,Male,78,O+,VA,NaN,Private,Type 2 Diabetes,173.300000,86.9,120,79,70,2025-04-28
24,PT100024,Noor,Anderson,Male,33,O+,MA,Never,Private,GERD,185.600000,62.0,106,66,62,2025-01-22

In [165]:
P_record.head(20)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.300000,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.200000,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.100000,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.500000,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.700000,65.0,117,59,72,2024-11-15
5,PT100005,Karen,Rodriguez,Male,78,O+,NY,Former,Medicaid,Depression,181.800000,100.9,115,69,76,2024-02-25
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.100000,74.0,124,62,70,2025-03-16
7,PT100007,Jennifer,Garcia,Male,67,B+,MA,Never,Private,Asthma,179.600000,76.4,114,75,80,2023-06-10
8,PT100008,Sarah,Nguyen,Female,44,B+,AZ,Never,Private,Atrial Fibrillation,172.600000,93.0,118,75,90,2023-05-13
9,PT100009,John,Kim,Female,2,A+,MI,Former,Private,Hypertension,164.500000,72.1,127,81,95,2024-08-28
10,PT100010,Jennifer,Williams,Female,50,A+,MA,Never,Medicare,Hypertension,167.392153,77.8,117,95,66,2024-03-05
11,PT100011,Sarah,Brown,Male,4,B+,OH,Current,Private,Obesity,176.200000,89.4,117,88,88,2025-03-09
12,PT100012,Wei,Lee,Male,88,O+,MI,Former,Private,Depression,166.100000,51.4,107,61,82,2024-07-08
13,PT100013,Fatima,Khan,Male,57,A+,NC,Former,Private,Type 2 Diabetes,164.500000,70.4,104,87,87,2024-01-24
14,PT100014,Omar,Brown,Female,35,O+,NY,Never,Medicare,Obesity,179.300000,88.3,126,81,74,2023-06-24
15,PT100015,Ahmed,Davis,Female,46,O+,NY,Former,Private,Asthma,184.600000,76.0,131,79,73,2023-06-28
16,PT100016,Susan,Moore,Male,58,O+,AZ,Current,Medicare,Obesity,160.500000,98.5,99,80,86,2025-04-07
17,PT100017,Kwame,Brown,Female,24,AB+,TX,Never,Private,Depression,165.400000,49.8,139,82,86,2023-09-06
18,PT100018,Patricia,Hernandez,Male,27,AB+,PA,Never,VA,GERD,171.500000,48.0,139,72,94,2024-07-04
19,PT100019,Ingrid,Smith,Male,39,O+,MI,Never,Medicare,Chronic Kidney Disease,172.900000,87.3,143,78,77,2025-06-14

In [172]:
### Using each patient's height and weight, calculate their Body Mass Index (BMI). Then group patients 
##into standard categories (Underweight, Normal, Overweight, Obese) — how many patients fall into each category?

P_record['BMI']=round(P_record['weight_kg']/(P_record['height_cm']/100)**2)
P_record.head(1)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date,BMI
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19,35.0

In [166]:
print(P_record['weight_kg'].isna().sum())

48

In [180]:
def BMI_category(BMI):
    
    if pd.isna('BMI'):
        return 'unknown'
    elif BMI < 18.5:
        return 'underweight'
    elif BMI < 24.9:
        return 'Healthy'
    elif BMI < 29.9:
        return 'overweight'
    else:
        return 'Obese'

P_record['category']=P_record['BMI'].apply(BMI_category)
P_record[['BMI', 'category']].head()

    BMI     category
0  35.0        Obese
1  14.0  underweight
2  21.0      Healthy
3  22.0      Healthy
4  23.0      Healthy

In [181]:
P_record.head(5)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date,BMI,category
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19,35.0,Obese
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16,14.0,underweight
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11,21.0,Healthy
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,65.0,147,77,99,2023-08-09,22.0,Healthy
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15,23.0,Healthy

In [186]:
P_record['category'].value_counts()

category
Obese          407
Healthy        351
overweight     340
underweight    102
Name: count, dtype: int64

In [187]:
###  What is the average age of patients for each primary condition? 
##Which conditions tend to affect older vs. younger patients?

P_record['primary_condition'].value_counts()

primary_condition
Hypertension               177
Type 2 Diabetes            170
Obesity                    132
Depression                 124
Anxiety Disorder            94
Coronary Artery Disease     93
Asthma                      90
Osteoarthritis              62
COPD                        52
Atrial Fibrillation         51
Hypothyroidism              51
Chronic Kidney Disease      42
GERD                        30
Migraine                    27
Name: count, dtype: int64

In [192]:
P_record.groupby('primary_condition')['age'].mean()

primary_condition
Anxiety Disorder           46.319149
Asthma                     46.400000
Atrial Fibrillation        48.509804
COPD                       48.826923
Chronic Kidney Disease     43.142857
Coronary Artery Disease    51.505376
Depression                 47.137097
GERD                       48.300000
Hypertension               45.406780
Hypothyroidism             46.274510
Migraine                   42.444444
Obesity                    48.030303
Osteoarthritis             44.774194
Type 2 Diabetes            47.647059
Name: age, dtype: float64

In [193]:
P_record['age']

0        0
1       53
2       70
3       52
4       36
        ..
1195    27
1196    32
1197    52
1198    27
1199    59
Name: age, Length: 1200, dtype: int64

In [197]:
def age_category(age):
    if age < 10:
        return 'toddler'
    elif age < 35:
        return 'younger_p'
    else:
        return 'older'

P_record['affected_population']= P_record['age'].apply(age_category)
P_record.head(5)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date,BMI,category,affected_population
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19,35.0,Obese,toddler
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16,14.0,underweight,older
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11,21.0,Healthy,older
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,65.0,147,77,99,2023-08-09,22.0,Healthy,older
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15,23.0,Healthy,older