In [5]:
import pandas as pd
import numpy as np

PCT=pd.read_csv('clinical_trials.csv')
PCT.head()

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
0,SUBJ200000,PT100346,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,200.0,2023-04-12,24,False,NaN,True
1,SUBJ200001,PT100311,RESPIRA-3 (Asthma Biologic),TRIAL-005,Placebo,50.0,2024-03-28,4,False,Severe - Hospitalization,True
2,SUBJ200002,PT101154,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Treatment,100.0,2025-01-07,8,False,Moderate - Fatigue,True
3,SUBJ200003,PT101061,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,150.0,2023-02-05,8,False,Mild - Headache,True
4,SUBJ200004,PT100094,CARDIA-9 (Heart Failure),TRIAL-002,Active Comparator,200.0,2023-11-18,12,True,Moderate - Fatigue,False

In [6]:
category=PCT.groupby('study_arm')

In [7]:
## applying builtin aggregation functions on groupby objects

category.sum()

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,SUBJ200004SUBJ200008SUBJ200010SUBJ200024SUBJ20...,PT100094PT100294PT100107PT100189PT100640PT1001...,CARDIA-9 (Heart Failure)NEURA-12 (Alzheimer's)...,TRIAL-002TRIAL-004TRIAL-004TRIAL-003TRIAL-005T...,15200.0,2023-11-182024-07-152025-04-112024-08-252023-1...,2812,74,Moderate - FatigueModerate - FatigueMild - Nau...,121
Placebo,SUBJ200001SUBJ200005SUBJ200009SUBJ200012SUBJ20...,PT100311PT100916PT101035PT100857PT101028PT1010...,RESPIRA-3 (Asthma Biologic)CARDIA-9 (Heart Fai...,TRIAL-005TRIAL-002TRIAL-005TRIAL-001TRIAL-005T...,24100.0,2024-03-282023-07-012023-02-272024-01-022023-0...,4336,70,Severe - HospitalizationMild - HeadacheModerat...,188
Treatment,SUBJ200000SUBJ200002SUBJ200003SUBJ200006SUBJ20...,PT100346PT101154PT101061PT100274PT101021PT1000...,ONCO-217 (Lung Cancer)GLYCOX-4 (Type 2 Diabete...,TRIAL-001TRIAL-003TRIAL-001TRIAL-001TRIAL-001T...,25200.0,2023-04-122025-01-072023-02-052024-10-102023-0...,5076,142,Moderate - FatigueMild - HeadacheModerate - Ra...,203

In [11]:
category.min()

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,SUBJ200004,PT100007,CARDIA-9 (Heart Failure),TRIAL-001,50.0,2023-01-01,4,False,Mild - Headache,False
Placebo,SUBJ200001,PT100000,CARDIA-9 (Heart Failure),TRIAL-001,50.0,2023-01-14,4,False,Mild - Headache,False
Treatment,SUBJ200000,PT100008,CARDIA-9 (Heart Failure),TRIAL-001,50.0,2023-01-05,4,False,Mild - Headache,False

In [13]:
category['dosage_mg'].mean()

study_arm
Active Comparator    117.829457
Placebo              119.306931
Treatment            118.309859
Name: dosage_mg, dtype: float64

In [19]:

PCT.groupby('study_arm').sum()['adverse_event']

study_arm
Active Comparator    Moderate - FatigueModerate - FatigueMild - Nau...
Placebo              Severe - HospitalizationMild - HeadacheModerat...
Treatment            Moderate - FatigueMild - HeadacheModerate - Ra...
Name: adverse_event, dtype: str

In [22]:
### study arms with  with grouped with adverse events

PCT.groupby('study_arm')['adverse_event'].value_counts()

study_arm          adverse_event
Active Comparator  Moderate - Fatigue          21
                   Mild - Nausea               16
                   Mild - Headache             15
                   Moderate - Rash             13
                   Severe - Hospitalization     2
Placebo            Moderate - Fatigue          29
                   Mild - Headache             28
                   Mild - Nausea               24
                   Moderate - Rash             20
                   Severe - Hospitalization    13
Treatment          Mild - Nausea               30
                   Moderate - Fatigue          29
                   Mild - Headache             24
                   Moderate - Rash             13
                   Severe - Hospitalization     5
Name: count, dtype: int64

In [30]:
PCT.groupby('study_arm')['follow_up_weeks'].value_counts()

study_arm          follow_up_weeks
Active Comparator  4                  30
                   52                 30
                   12                 29
                   8                  26
                   24                 24
Placebo            12                 50
                   52                 46
                   4                  44
                   8                  41
                   24                 35
Treatment          8                  54
                   52                 54
                   12                 51
                   24                 44
                   4                  42
Name: count, dtype: int64

In [31]:
PCT.groupby('study_arm')['follow_up_weeks'].mean()

study_arm
Active Comparator    20.230216
Placebo              20.074074
Treatment            20.718367
Name: follow_up_weeks, dtype: float64

In [32]:
PCT.groupby('study_arm')['dosage_mg'].mean()

study_arm
Active Comparator    117.829457
Placebo              119.306931
Treatment            118.309859
Name: dosage_mg, dtype: float64

In [33]:
PCT.groupby('study_arm')['dosage_mg'].value_counts()

study_arm          dosage_mg
Active Comparator  150.0        41
                   100.0        39
                   50.0         31
                   200.0        18
Placebo            100.0        73
                   150.0        48
                   50.0         44
                   200.0        37
Treatment          100.0        89
                   150.0        59
                   50.0         37
                   200.0        28
Name: count, dtype: int64

In [35]:
PCT.groupby('study_arm')['dosage_mg'].sum().sort_values()

study_arm
Active Comparator    15200.0
Placebo              24100.0
Treatment            25200.0
Name: dosage_mg, dtype: float64

In [36]:
PCT.groupby('adverse_event')['dosage_mg'].sum().sort_values()

adverse_event
Severe - Hospitalization    1600.0
Moderate - Rash             4750.0
Mild - Nausea               7150.0
Mild - Headache             7750.0
Moderate - Fatigue          8650.0
Name: dosage_mg, dtype: float64

In [42]:
PCT.groupby('adverse_event')['dosage_mg'].value_counts()

adverse_event             dosage_mg
Mild - Headache           100.0        19
                          50.0         16
                          150.0        15
                          200.0        14
Mild - Nausea             100.0        27
                          150.0        16
                          50.0         13
                          200.0         7
Moderate - Fatigue        100.0        30
                          150.0        18
                          50.0         15
                          200.0        11
Moderate - Rash           100.0        16
                          150.0        11
                          50.0         10
                          200.0         5
Severe - Hospitalization  100.0         8
                          50.0          6
                          150.0         2
                          200.0         1
Name: count, dtype: int64

In [43]:
PCT.groupby('adverse_event')['dosage_mg'].value_counts().sort_values(ascending=False)

adverse_event             dosage_mg
Moderate - Fatigue        100.0        30
Mild - Nausea             100.0        27
Mild - Headache           100.0        19
Moderate - Fatigue        150.0        18
Moderate - Rash           100.0        16
Mild - Nausea             150.0        16
Mild - Headache           50.0         16
                          150.0        15
Moderate - Fatigue        50.0         15
Mild - Headache           200.0        14
Mild - Nausea             50.0         13
Moderate - Fatigue        200.0        11
Moderate - Rash           150.0        11
                          50.0         10
Severe - Hospitalization  100.0         8
Mild - Nausea             200.0         7
Severe - Hospitalization  50.0          6
Moderate - Rash           200.0         5
Severe - Hospitalization  150.0         2
                          200.0         1
Name: count, dtype: int64

In [44]:
PCT.groupby('subject_id')['follow_up_weeks'].sum()

subject_id
SUBJ200000    24
SUBJ200001     4
SUBJ200002     8
SUBJ200003     8
SUBJ200004    12
              ..
SUBJ200595    24
SUBJ200596    24
SUBJ200597    12
SUBJ200598    52
SUBJ200599    52
Name: follow_up_weeks, Length: 600, dtype: int64

In [48]:
## subject with higest follow up

PCT.groupby('subject_id')['follow_up_weeks'].sum().sort_values(ascending=False).head(1)

subject_id
SUBJ200599    52
Name: follow_up_weeks, dtype: int64

In [52]:


PCT.groupby('study_arm')['follow_up_weeks'].max()

study_arm
Active Comparator    52
Placebo              52
Treatment            52
Name: follow_up_weeks, dtype: int64

In [53]:
PCT.groupby('subject_id')['trial_name'].value_counts()

subject_id  trial_name
SUBJ200000  ONCO-217 (Lung Cancer)         1
SUBJ200001  RESPIRA-3 (Asthma Biologic)    1
SUBJ200002  GLYCOX-4 (Type 2 Diabetes)     1
SUBJ200003  ONCO-217 (Lung Cancer)         1
SUBJ200004  CARDIA-9 (Heart Failure)       1
                                          ..
SUBJ200595  CARDIA-9 (Heart Failure)       1
SUBJ200596  CARDIA-9 (Heart Failure)       1
SUBJ200597  ONCO-217 (Lung Cancer)         1
SUBJ200598  NEURA-12 (Alzheimer's)         1
SUBJ200599  ONCO-217 (Lung Cancer)         1
Name: count, Length: 600, dtype: int64

In [57]:
PCT['completed_trial'].value_counts()

completed_trial
True     512
False     88
Name: count, dtype: int64

In [60]:
PCT.groupby('subject_id')['completed_trial'].count().head(20)

subject_id
SUBJ200000    1
SUBJ200001    1
SUBJ200002    1
SUBJ200003    1
SUBJ200004    1
SUBJ200005    1
SUBJ200006    1
SUBJ200007    1
SUBJ200008    1
SUBJ200009    1
SUBJ200010    1
SUBJ200011    1
SUBJ200012    1
SUBJ200013    1
SUBJ200014    1
SUBJ200015    1
SUBJ200016    1
SUBJ200017    1
SUBJ200018    1
SUBJ200019    1
Name: completed_trial, dtype: int64

###  Groupby methods and attributes

In [61]:
## number of groups formed----------> .unique() can also work the same

len(PCT.groupby('study_arm'))

3

In [62]:
len(PCT.groupby('adverse_event'))

5

In [63]:
## number of items in each adverse event group -----> done by .size() and value counts()
## size does the alphabetical order of index

PCT.groupby('adverse_event').size()

adverse_event
Mild - Headache             67
Mild - Nausea               70
Moderate - Fatigue          79
Moderate - Rash             46
Severe - Hospitalization    20
dtype: int64

In [64]:
PCT['adverse_event'].value_counts()

adverse_event
Moderate - Fatigue          79
Mild - Nausea               70
Mild - Headache             67
Moderate - Rash             46
Severe - Hospitalization    20
Name: count, dtype: int64

In [65]:
### gives the first pateint under the each adverse event group

PCT.groupby('adverse_event').first()

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,completed_trial
adverse_event,,,,,,,,,,
Mild - Headache,SUBJ200003,PT101061,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,150.0,2023-02-05,8,False,True
Mild - Nausea,SUBJ200022,PT100715,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,100.0,2025-04-19,24,True,True
Moderate - Fatigue,SUBJ200002,PT101154,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Treatment,100.0,2025-01-07,8,False,True
Moderate - Rash,SUBJ200011,PT100008,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,150.0,2023-10-15,8,False,True
Severe - Hospitalization,SUBJ200001,PT100311,RESPIRA-3 (Asthma Biologic),TRIAL-005,Placebo,50.0,2024-03-28,4,False,True

In [68]:
PCT.groupby('adverse_event').last()

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,completed_trial
adverse_event,,,,,,,,,,
Mild - Headache,SUBJ200597,PT100169,ONCO-217 (Lung Cancer),TRIAL-001,Placebo,50.0,2023-07-29,12,False,True
Mild - Nausea,SUBJ200565,PT100039,RESPIRA-3 (Asthma Biologic),TRIAL-005,Placebo,50.0,2025-04-09,4,True,False
Moderate - Fatigue,SUBJ200599,PT100010,ONCO-217 (Lung Cancer),TRIAL-001,Placebo,50.0,2024-04-20,52,False,True
Moderate - Rash,SUBJ200552,PT100366,NEURA-12 (Alzheimer's),TRIAL-004,Active Comparator,200.0,2023-11-04,4,False,True
Severe - Hospitalization,SUBJ200590,PT100055,RESPIRA-3 (Asthma Biologic),TRIAL-005,Placebo,150.0,2024-07-20,24,True,True

In [66]:
PCT.groupby('study_arm').first()

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,SUBJ200004,PT100094,CARDIA-9 (Heart Failure),TRIAL-002,200.0,2023-11-18,12,True,Moderate - Fatigue,False
Placebo,SUBJ200001,PT100311,RESPIRA-3 (Asthma Biologic),TRIAL-005,50.0,2024-03-28,4,False,Severe - Hospitalization,True
Treatment,SUBJ200000,PT100346,ONCO-217 (Lung Cancer),TRIAL-001,200.0,2023-04-12,24,False,Moderate - Fatigue,True

In [67]:
PCT.groupby('study_arm').last()

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,SUBJ200596,PT100198,CARDIA-9 (Heart Failure),TRIAL-002,150.0,2023-04-16,24,True,Moderate - Fatigue,True
Placebo,SUBJ200599,PT100010,ONCO-217 (Lung Cancer),TRIAL-001,50.0,2024-04-20,52,False,Moderate - Fatigue,True
Treatment,SUBJ200595,PT100023,CARDIA-9 (Heart Failure),TRIAL-002,100.0,2025-02-11,24,False,Moderate - Fatigue,False

In [71]:
PCT.groupby('adverse_event').nth(2)

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
17,SUBJ200017,PT100811,RESPIRA-3 (Asthma Biologic),TRIAL-005,Treatment,50.0,2023-04-11,4,False,Mild - Headache,False
21,SUBJ200021,PT100799,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,100.0,2023-08-31,12,False,Moderate - Fatigue,True
36,SUBJ200036,PT100034,CARDIA-9 (Heart Failure),TRIAL-002,Placebo,150.0,2024-09-08,24,False,Moderate - Rash,True
40,SUBJ200040,PT100460,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,100.0,2023-08-07,24,True,Mild - Nausea,True
42,SUBJ200042,PT100026,ONCO-217 (Lung Cancer),TRIAL-001,Active Comparator,50.0,2024-10-02,8,True,Severe - Hospitalization,False

In [73]:
PCT.groupby('study_arm').nth(5)

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
11,SUBJ200011,PT100008,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,150.0,2023-10-15,8,False,Moderate - Rash,True
16,SUBJ200016,PT101048,NEURA-12 (Alzheimer's),TRIAL-004,Placebo,100.0,2025-03-25,24,False,NaN,True
35,SUBJ200035,PT100116,RESPIRA-3 (Asthma Biologic),TRIAL-005,Active Comparator,150.0,2024-03-22,4,True,Mild - Nausea,True

In [75]:
### Get group function

A_E=PCT.groupby('study_arm')

A_E.get_group('Treatment')

###  can also be done by--> PCT[PCT[study_arm]=='Treatment']

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
0,SUBJ200000,PT100346,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,200.0,2023-04-12,24,False,NaN,True
2,SUBJ200002,PT101154,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Treatment,100.0,2025-01-07,8,False,Moderate - Fatigue,True
3,SUBJ200003,PT101061,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,150.0,2023-02-05,8,False,Mild - Headache,True
6,SUBJ200006,PT100274,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,150.0,2024-10-10,12,False,NaN,True
7,SUBJ200007,PT101021,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,200.0,2023-05-07,52,True,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
587,SUBJ200587,PT100175,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,150.0,2024-07-02,24,True,NaN,True
589,SUBJ200589,PT101166,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Treatment,100.0,2023-01-09,12,False,NaN,True
593,SUBJ200593,PT100176,RESPIRA-3 (Asthma Biologic),TRIAL-005,Treatment,100.0,2025-05-28,4,False,NaN,True
594,SUBJ200594,PT100697,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,200.0,2023-08-03,52,False,NaN,False
595,SUBJ200595,PT100023,CARDIA-9 (Heart Failure),TRIAL-002,Treatment,100.0,2025-02-11,24,False,Moderate - Fatigue,False

In [76]:
A_E.describe()

                  dosage_mg                                                    \
                      count        mean        std   min    25%    50%    75%
study_arm
Active Comparator     129.0  117.829457  49.921207  50.0  100.0  100.0  150.0
Placebo               202.0  119.306931  51.092686  50.0  100.0  100.0  150.0
Treatment             213.0  118.309859  45.999977  50.0  100.0  100.0  150.0

                         follow_up_weeks                                  \
                     max           count       mean        std  min  25%
study_arm
Active Comparator  200.0           139.0  20.230216  17.932368  4.0  8.0
Placebo            200.0           216.0  20.074074  17.788266  4.0  8.0
Treatment          200.0           245.0  20.718367  17.841006  4.0  8.0


                    50%   75%   max
study_arm
Active Comparator  12.0  24.0  52.0
Placebo            12.0  24.0  52.0
Treatment          12.0  24.0  52.0

In [77]:
PCT.groupby('adverse_event').describe()

                         dosage_mg                                             \
                             count        mean        std   min    25%    50%
adverse_event
Mild - Headache               64.0  121.093750  54.775652  50.0   87.5  100.0
Mild - Nausea                 63.0  113.492063  45.971896  50.0  100.0  100.0
Moderate - Fatigue            74.0  116.891892  48.453499  50.0  100.0  100.0
Moderate - Rash               42.0  113.095238  48.211328  50.0  100.0  100.0
Severe - Hospitalization      17.0   94.117647  42.874646  50.0   50.0  100.0

                                       follow_up_weeks                        \
                            75%    max           count       mean        std
adverse_event
Mild - Headache           150.0  200.0            67.0  18.567164  17.707406
Mild - Nausea             150.0  200.0            70.0  21.542857  18.998616
Moderate - Fatigue        150.0  200.0            79.0  20.658228  18.346303
Moderate - Rash           150.0  200.0            46.0  14.782609  13.168840
Severe - Hospitalization  100.0  200.0            20.0  23.600000  18.024545


                          min  25%   50%   75%   max
adverse_event
Mild - Headache           4.0  6.0  12.0  24.0  52.0
Mild - Nausea             4.0  8.0  12.0  45.0  52.0
Moderate - Fatigue        4.0  8.0  12.0  24.0  52.0
Moderate - Rash           4.0  8.0  12.0  12.0  52.0
Severe - Hospitalization  4.0  8.0  18.0  31.0  52.0

In [78]:
PCT.groupby('adverse_event').sample()

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
454,SUBJ200454,PT100706,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Placebo,50.0,2024-02-19,24,True,Mild - Headache,True
487,SUBJ200487,PT100879,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Treatment,100.0,2025-03-15,52,True,Mild - Nausea,False
21,SUBJ200021,PT100799,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,100.0,2023-08-31,12,False,Moderate - Fatigue,True
12,SUBJ200012,PT100857,ONCO-217 (Lung Cancer),TRIAL-001,Placebo,200.0,2024-01-02,8,False,Moderate - Rash,True
125,SUBJ200125,PT100045,CARDIA-9 (Heart Failure),TRIAL-002,Placebo,50.0,2023-02-04,24,False,Severe - Hospitalization,True

In [79]:
A_E.sample()

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
219,SUBJ200219,PT100419,GLYCOX-4 (Type 2 Diabetes),TRIAL-003,Active Comparator,100.0,2024-10-20,12,True,NaN,True
561,SUBJ200561,PT100143,NEURA-12 (Alzheimer's),TRIAL-004,Placebo,100.0,2024-04-15,52,True,NaN,False
594,SUBJ200594,PT100697,ONCO-217 (Lung Cancer),TRIAL-001,Treatment,200.0,2023-08-03,52,False,NaN,False

In [81]:
A_E.sample(2, replace=True)

,subject_id,patient_id,trial_name,trial_id,study_arm,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
450,SUBJ200450,PT100536,CARDIA-9 (Heart Failure),TRIAL-002,Active Comparator,150.0,2025-04-30,52,True,Mild - Headache,True
533,SUBJ200533,PT100064,NEURA-12 (Alzheimer's),TRIAL-004,Active Comparator,150.0,2023-08-30,12,False,NaN,True
249,SUBJ200249,PT100439,ONCO-217 (Lung Cancer),TRIAL-001,Placebo,100.0,2024-12-15,52,True,Moderate - Fatigue,True
257,SUBJ200257,PT100246,CARDIA-9 (Heart Failure),TRIAL-002,Placebo,50.0,2024-03-28,4,False,Mild - Nausea,True
226,SUBJ200226,PT101060,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,NaN,2024-06-04,8,False,Moderate - Rash,False
402,SUBJ200402,PT101015,NEURA-12 (Alzheimer's),TRIAL-004,Treatment,100.0,2023-08-27,12,True,NaN,False

In [82]:
A_E.nunique()

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,139,139,5,5,4,126,5,2,5,2
Placebo,216,216,5,5,4,195,5,2,5,2
Treatment,245,245,5,5,4,217,5,2,5,2

In [83]:
## aggregate function

A_E.sum()     ## this is less useful

,subject_id,patient_id,trial_name,trial_id,dosage_mg,enrollment_date,follow_up_weeks,responded_to_treatment,adverse_event,completed_trial
study_arm,,,,,,,,,,
Active Comparator,SUBJ200004SUBJ200008SUBJ200010SUBJ200024SUBJ20...,PT100094PT100294PT100107PT100189PT100640PT1001...,CARDIA-9 (Heart Failure)NEURA-12 (Alzheimer's)...,TRIAL-002TRIAL-004TRIAL-004TRIAL-003TRIAL-005T...,15200.0,2023-11-182024-07-152025-04-112024-08-252023-1...,2812,74,Moderate - FatigueModerate - FatigueMild - Nau...,121
Placebo,SUBJ200001SUBJ200005SUBJ200009SUBJ200012SUBJ20...,PT100311PT100916PT101035PT100857PT101028PT1010...,RESPIRA-3 (Asthma Biologic)CARDIA-9 (Heart Fai...,TRIAL-005TRIAL-002TRIAL-005TRIAL-001TRIAL-005T...,24100.0,2024-03-282023-07-012023-02-272024-01-022023-0...,4336,70,Severe - HospitalizationMild - HeadacheModerat...,188
Treatment,SUBJ200000SUBJ200002SUBJ200003SUBJ200006SUBJ20...,PT100346PT101154PT101061PT100274PT101021PT1000...,ONCO-217 (Lung Cancer)GLYCOX-4 (Type 2 Diabete...,TRIAL-001TRIAL-003TRIAL-001TRIAL-001TRIAL-001T...,25200.0,2023-04-122025-01-072023-02-052024-10-102023-0...,5076,142,Moderate - FatigueMild - HeadacheModerate - Ra...,203

In [84]:
### aggregation

A_E.agg({'dosage_mg':'mean', 'follow_up_weeks':'sum'})

                    dosage_mg  follow_up_weeks
study_arm
Active Comparator  117.829457             2812
Placebo            119.306931             4336
Treatment          118.309859             5076

In [96]:
A_t=PCT.groupby('study_arm')['dosage_mg']
A_t.agg(['min', 'max', 'mean', 'median'])

                    min    max        mean  median
study_arm
Active Comparator  50.0  200.0  117.829457   100.0
Placebo            50.0  200.0  119.306931   100.0
Treatment          50.0  200.0  118.309859   100.0

In [97]:
###  can perform a set of functions on each numerical column
A_t=PCT.groupby('study_arm')['follow_up_weeks']

A_t.agg(['min', 'max', 'mean', 'median'])

                   min  max       mean  median
study_arm
Active Comparator    4   52  20.230216    12.0
Placebo              4   52  20.074074    12.0
Treatment            4   52  20.718367    12.0

In [99]:
###  adding up both processes

A_E.agg({'dosage_mg':['mean','min', 'min'], 'follow_up_weeks':['sum', 'max', 'min']})

                    dosage_mg             follow_up_weeks
                         mean   min   min             sum max min
study_arm
Active Comparator  117.829457  50.0  50.0            2812  52   4
Placebo            119.306931  50.0  50.0            4336  52   4
Treatment          118.309859  50.0  50.0            5076  52   4

In [101]:
## looping on groups

for group,data in A_E:
    print(data)

     subject_id patient_id                   trial_name   trial_id  \
4    SUBJ200004   PT100094     CARDIA-9 (Heart Failure)  TRIAL-002
8    SUBJ200008   PT100294       NEURA-12 (Alzheimer's)  TRIAL-004
10   SUBJ200010   PT100107       NEURA-12 (Alzheimer's)  TRIAL-004
24   SUBJ200024   PT100189   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003
31   SUBJ200031   PT100640  RESPIRA-3 (Asthma Biologic)  TRIAL-005
..          ...        ...                          ...        ...
572  SUBJ200572   PT100335       NEURA-12 (Alzheimer's)  TRIAL-004
574  SUBJ200574   PT100591   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003
583  SUBJ200583   PT100647     CARDIA-9 (Heart Failure)  TRIAL-002
584  SUBJ200584   PT100488       ONCO-217 (Lung Cancer)  TRIAL-001
596  SUBJ200596   PT100198     CARDIA-9 (Heart Failure)  TRIAL-002

             study_arm  dosage_mg enrollment_date  follow_up_weeks  \
4    Active Comparator      200.0      2023-11-18               12
8    Active Comparator      100.0      2024-07-15                8
10   Active Comparator      200.0      2025-04-11                4
24   Active Comparator      150.0      2024-08-25                4
31   Active Comparator      100.0      2023-10-30               12
..                 ...        ...             ...              ...
572  Active Comparator      100.0      2025-01-23                4
574  Active Comparator       50.0      2023-11-28               52
583  Active Comparator      200.0      2023-03-16                4
584  Active Comparator      150.0      2024-12-01                4
596  Active Comparator        NaN      2023-04-16               24

     responded_to_treatment       adverse_event  completed_trial
4                      True  Moderate - Fatigue            False
8                     False                 NaN             True
10                     True                 NaN             True
24                     True  Moderate - Fatigue            False
31                    False                 NaN             True
..                      ...                 ...              ...
572                    True                 NaN             True
574                   False                 NaN             True
583                    True                 NaN             True
584                   False  Moderate - Fatigue             True
596                    True                 NaN             True

[139 rows x 11 columns]
     subject_id patient_id                   trial_name   trial_id study_arm  \
1    SUBJ200001   PT100311  RESPIRA-3 (Asthma Biologic)  TRIAL-005   Placebo
5    SUBJ200005   PT100916     CARDIA-9 (Heart Failure)  TRIAL-002   Placebo
9    SUBJ200009   PT101035  RESPIRA-3 (Asthma Biologic)  TRIAL-005   Placebo
12   SUBJ200012   PT100857       ONCO-217 (Lung Cancer)  TRIAL-001   Placebo
15   SUBJ200015   PT101028  RESPIRA-3 (Asthma Biologic)  TRIAL-005   Placebo
..          ...        ...                          ...        ...       ...
591  SUBJ200591   PT100658   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003   Placebo
592  SUBJ200592   PT100509       NEURA-12 (Alzheimer's)  TRIAL-004   Placebo
597  SUBJ200597   PT100169       ONCO-217 (Lung Cancer)  TRIAL-001   Placebo
598  SUBJ200598   PT100245       NEURA-12 (Alzheimer's)  TRIAL-004   Placebo
599  SUBJ200599   PT100010       ONCO-217 (Lung Cancer)  TRIAL-001   Placebo

     dosage_mg enrollment_date  follow_up_weeks  responded_to_treatment  \
1         50.0      2024-03-28                4                   False
5        150.0      2023-07-01               52                    True
9         50.0      2023-02-27                8                    True
12       200.0      2024-01-02                8                   False
15       100.0      2023-04-14               12                   False
..         ...             ...              ...                     ...
591      200.0      2024-04-08                4                   False
592      200.0      2023-02-09                8                    True
597       50.0      2023-07-29               12                   False
598      150.0      2024-04-20               52                    True
599       50.0      2024-04-20               52                   False

                adverse_event  completed_trial
1    Severe - Hospitalization             True
5                         NaN             True
9             Mild - Headache            False
12            Moderate - Rash             True
15                        NaN             True
..                        ...              ...
591           Mild - Headache             True
592                       NaN            False
597           Mild - Headache             True
598                       NaN             True
599        Moderate - Fatigue             True

[216 rows x 11 columns]
     subject_id patient_id                   trial_name   trial_id  study_arm  \
0    SUBJ200000   PT100346       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
2    SUBJ200002   PT101154   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003  Treatment
3    SUBJ200003   PT101061       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
6    SUBJ200006   PT100274       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
7    SUBJ200007   PT101021       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
..          ...        ...                          ...        ...        ...
587  SUBJ200587   PT100175       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
589  SUBJ200589   PT101166   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003  Treatment
593  SUBJ200593   PT100176  RESPIRA-3 (Asthma Biologic)  TRIAL-005  Treatment
594  SUBJ200594   PT100697       ONCO-217 (Lung Cancer)  TRIAL-001  Treatment
595  SUBJ200595   PT100023     CARDIA-9 (Heart Failure)  TRIAL-002  Treatment

     dosage_mg enrollment_date  follow_up_weeks  responded_to_treatment  \
0        200.0      2023-04-12               24                   False
2        100.0      2025-01-07                8                   False
3        150.0      2023-02-05                8                   False
6        150.0      2024-10-10               12                   False
7        200.0      2023-05-07               52                    True
..         ...             ...              ...                     ...
587      150.0      2024-07-02               24                    True
589      100.0      2023-01-09               12                   False
593      100.0      2025-05-28                4                   False
594      200.0      2023-08-03               52                   False
595      100.0      2025-02-11               24                   False

          adverse_event  completed_trial
0                   NaN             True
2    Moderate - Fatigue             True
3       Mild - Headache             True
6                   NaN             True
7                   NaN            False
..                  ...              ...
587                 NaN             True
589                 NaN             True
593                 NaN             True
594                 NaN            False
595  Moderate - Fatigue            False

[245 rows x 11 columns]

In [105]:
for group,data in A_E:
    print(data['follow_up_weeks'].min())

4
4
4

In [108]:
for group,data in A_E:
    print(data['dosage_mg'].min())

50.0
50.0
50.0

In [112]:
### subject-id in each arm with highest follow up weeks

A_P=PCT.groupby('study_arm')

for group,data in A_P:
    print(group)
    print(data[data['follow_up_weeks']== data['follow_up_weeks'].max()])[['subject_id','follow_up_weeks']]

Active Comparator
     subject_id patient_id                   trial_name   trial_id  \
45   SUBJ200045   PT100377     CARDIA-9 (Heart Failure)  TRIAL-002
90   SUBJ200090   PT100378  RESPIRA-3 (Asthma Biologic)  TRIAL-005
110  SUBJ200110   PT100210   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003
139  SUBJ200139   PT100503  RESPIRA-3 (Asthma Biologic)  TRIAL-005
169  SUBJ200169   PT101156     CARDIA-9 (Heart Failure)  TRIAL-002
178  SUBJ200178   PT100621       NEURA-12 (Alzheimer's)  TRIAL-004
195  SUBJ200195   PT100869  RESPIRA-3 (Asthma Biologic)  TRIAL-005
218  SUBJ200218   PT100199       NEURA-12 (Alzheimer's)  TRIAL-004
238  SUBJ200238   PT100982       NEURA-12 (Alzheimer's)  TRIAL-004
241  SUBJ200241   PT100829  RESPIRA-3 (Asthma Biologic)  TRIAL-005
271  SUBJ200271   PT101134       NEURA-12 (Alzheimer's)  TRIAL-004
346  SUBJ200346   PT101056   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003
362  SUBJ200362   PT100952     CARDIA-9 (Heart Failure)  TRIAL-002
374  SUBJ200374   PT100864  RESPIRA-3 (Asthma Biologic)  TRIAL-005
385  SUBJ200385   PT101169   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003
412  SUBJ200412   PT100507     CARDIA-9 (Heart Failure)  TRIAL-002
421  SUBJ200421   PT100028       NEURA-12 (Alzheimer's)  TRIAL-004
435  SUBJ200435   PT100804       NEURA-12 (Alzheimer's)  TRIAL-004
438  SUBJ200438   PT100937       NEURA-12 (Alzheimer's)  TRIAL-004
443  SUBJ200443   PT100900       NEURA-12 (Alzheimer's)  TRIAL-004
446  SUBJ200446   PT100920     CARDIA-9 (Heart Failure)  TRIAL-002
450  SUBJ200450   PT100536     CARDIA-9 (Heart Failure)  TRIAL-002
463  SUBJ200463   PT100562       ONCO-217 (Lung Cancer)  TRIAL-001
506  SUBJ200506   PT100151       NEURA-12 (Alzheimer's)  TRIAL-004
508  SUBJ200508   PT100348       NEURA-12 (Alzheimer's)  TRIAL-004
510  SUBJ200510   PT101179  RESPIRA-3 (Asthma Biologic)  TRIAL-005
511  SUBJ200511   PT100431  RESPIRA-3 (Asthma Biologic)  TRIAL-005
520  SUBJ200520   PT100893       ONCO-217 (Lung Cancer)  TRIAL-001
547  SUBJ200547   PT100231     CARDIA-9 (Heart Failure)  TRIAL-002
574  SUBJ200574   PT100591   GLYCOX-4 (Type 2 Diabetes)  TRIAL-003

             study_arm  dosage_mg enrollment_date  follow_up_weeks  \
45   Active Comparator      100.0      2025-04-15               52
90   Active Comparator      150.0      2023-03-22               52
110  Active Comparator      150.0      2023-06-22               52
139  Active Comparator      100.0      2024-07-21               52
169  Active Comparator      100.0      2023-08-24               52
178  Active Comparator      100.0      2024-07-14               52
195  Active Comparator      100.0      2025-05-10               52
218  Active Comparator      200.0      2023-03-10               52
238  Active Comparator      150.0      2024-06-26               52
241  Active Comparator      100.0      2024-12-17               52
271  Active Comparator       50.0      2023-07-14               52
346  Active Comparator       50.0      2023-07-19               52
362  Active Comparator      150.0      2024-05-23               52
374  Active Comparator      100.0      2025-01-03               52
385  Active Comparator      100.0      2024-04-30               52
412  Active Comparator      100.0      2025-04-14               52
421  Active Comparator      200.0      2024-10-14               52
435  Active Comparator      150.0      2025-02-06               52
438  Active Comparator      100.0      2023-01-19               52
443  Active Comparator      150.0      2023-11-12               52
446  Active Comparator      150.0      2023-08-29               52
450  Active Comparator      150.0      2025-04-30               52
463  Active Comparator      100.0      2024-04-30               52
506  Active Comparator      100.0      2023-04-11               52
508  Active Comparator      150.0      2024-08-29               52
510  Active Comparator      100.0      2024-10-29               52
511  Active Comparator      100.0      2023-03-19               52
520  Active Comparator        NaN      2023-06-24               52
547  Active Comparator       50.0      2024-01-22               52
574  Active Comparator       50.0      2023-11-28               52

     responded_to_treatment       adverse_event  completed_trial
45                     True  Moderate - Fatigue             True
90                     True                 NaN             True
110                   False                 NaN             True
139                    True                 NaN            False
169                   False                 NaN             True
178                   False       Mild - Nausea             True
195                   False       Mild - Nausea             True
218                    True                 NaN             True
238                   False                 NaN             True
241                    True  Moderate - Fatigue            False
271                   False  Moderate - Fatigue             True
346                   False                 NaN             True
362                   False                 NaN             True
374                    True  Moderate - Fatigue             True
385                   False                 NaN             True
412                   False                 NaN             True
421                   False       Mild - Nausea            False
435                    True     Mild - Headache             True
438                    True       Mild - Nausea             True
443                   False       Mild - Nausea             True
446                    True                 NaN             True
450                    True     Mild - Headache             True
463                    True                 NaN             True
506                   False                 NaN             True
508                    True                 NaN             True
510                    True                 NaN             True
511                   False                 NaN             True
520                   False       Mild - Nausea             True
547                    True                 NaN             True
574                   False                 NaN             True

TypeError: 'NoneType' object is not subscriptable

In [115]:
### apply function-----> split. apply. combine strategy

PCT.groupby('study_arm')['dosage_mg'].apply(min)

study_arm
Active Comparator    50.0
Placebo              50.0
Treatment            50.0
Name: dosage_mg, dtype: float64

In [116]:
### using pateint record dataset

P_record=pd.read_csv('patient_records.csv')
P_record.head(12)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
5,PT100005,Karen,Rodriguez,Male,78,O+,NY,Former,Medicaid,Depression,181.8,100.9,115,69,76,2024-02-25
6,PT100006,Karen,Gonzalez,Male,35,A+,NC,NaN,Private,Anxiety Disorder,180.1,74.0,124,62,70,2025-03-16
7,PT100007,Jennifer,Garcia,Male,67,B+,MA,Never,Private,Asthma,179.6,76.4,114,75,80,2023-06-10
8,PT100008,Sarah,Nguyen,Female,44,B+,AZ,Never,Private,Atrial Fibrillation,172.6,93.0,118,75,90,2023-05-13
9,PT100009,John,Kim,Female,2,A+,MI,Former,Private,Hypertension,164.5,72.1,127,81,95,2024-08-28
10,PT100010,Jennifer,Williams,Female,50,A+,MA,Never,Medicare,Hypertension,NaN,77.8,117,95,66,2024-03-05
11,PT100011,Sarah,Brown,Male,4,B+,OH,Current,Private,Obesity,176.2,89.4,117,88,88,2025-03-09

In [127]:
## find the no of patients whose name starts with 's' for each group 'gender', 'blood type'

Group1=P_record.groupby(['gender', 'blood_type'])['first_name']

def S_letter(group):
    return group.str.startswith('P').sum()
    

Group1.apply(S_letter)

gender  blood_type
Female  A+            16
        A-             1
        AB+            0
        AB-            0
        B+             2
        B-             1
        O+            11
        O-             3
Male    A+             7
        A-             1
        AB+            2
        AB-            1
        B+             4
        B-             0
        O+            10
        O-             1
Other   A+             0
        A-             0
        AB+            0
        B-             0
        O+             0
        O-             0
Name: first_name, dtype: int64

In [133]:
## find the first name of patients whose primary cond is asthma for each group 'gender' primary condition

def get_names(group):
    return list(group)
    
Asthma_only=P_record[P_record['primary_condition']== 'Asthma']
Group2=Asthma_only.groupby('gender')['first_name']

result=Group2.apply(get_names)
print(result)

gender
Female    [Ahmed, Sofia, Kwame, Yuki, Linda, Diego, Char...
Male      [John, Jennifer, Yuki, Yuki, Kwame, Sofia, Sar...
Other                      [William, Linda, Amara, Jessica]
Name: first_name, dtype: object

In [136]:
Asthma_only=P_record[P_record['primary_condition']== 'Asthma']['first_name'].tolist()
Asthma_only

['John',
 'Jennifer',
 'Ahmed',
 'Yuki',
 'Sofia',
 'Yuki',
 'Kwame',
 'Kwame',
 'Sofia',
 'Sarah',
 'Hiroshi',
 'James',
 'Yuki',
 'Linda',
 'Noor',
 'Diego',
 'Charles',
 'Omar',
 'Noor',
 'Elena',
 'Susan',
 'Charles',
 'Amara',
 'Linda',
 'James',
 'Barbara',
 'Amara',
 'Joseph',
 'Jessica',
 'William',
 'Michael',
 'Charles',
 'Sarah',
 'Linda',
 'Thomas',
 'Richard',
 'Karen',
 'Robert',
 'Susan',
 'Noor',
 'Fatima',
 'Amara',
 'Linda',
 'Omar',
 'Noor',
 'Amara',
 'Mary',
 'Mary',
 'David',
 'David',
 'Elena',
 'Richard',
 'Elizabeth',
 'William',
 'Sofia',
 'Sarah',
 'Carlos',
 'Robert',
 'Barbara',
 'Barbara',
 'Charles',
 'Sarah',
 'Charles',
 'Amara',
 'Diego',
 'David',
 'Susan',
 'Jennifer',
 'Carlos',
 'Elizabeth',
 'Carlos',
 'Elizabeth',
 'Karen',
 'Yuki',
 'Barbara',
 'Fatima',
 'Mary',
 'Priya',
 'Hiroshi',
 'Yuki',
 'David',
 'Robert',
 'Richard',
 'Jessica',
 'Linda',
 'Michael',
 'Wei',
 'Michael',
 'Mary',
 'David']

In [146]:
### find all the O+ pateints who have type2  daibetes

type2=P_record[(P_record['primary_condition']== 'Type 2 Diabetes') &  (P_record['blood_type']== 'O+')]
print(type2)

     patient_id first_name  last_name  gender  age blood_type state  \
0      PT100000      Sarah    Jackson    Male    0         O+    CA
4      PT100004      Priya      Rossi  Female   36         O+    AZ
23     PT100023      Amara  Rodriguez    Male   78         O+    VA
41     PT100041       Omar      Patel    Male    0         O+    FL
45     PT100045     Robert      Smith    Male   84         O+    GA
...         ...        ...        ...     ...  ...        ...   ...
1109   PT101109   Jennifer      Patel  Female   33         O+    OH
1117   PT101117     Ingrid     Miller    Male   85         O+    PA
1160   PT101160    Richard   Anderson  Female    6         O+    CA
1165   PT101165      Elena   Thompson    Male   24         O+    GA
1191   PT101191    Richard    Mueller  Female   28         O+    VA

     smoking_status insurance_type primary_condition  height_cm  weight_kg  \
0            Former        Private   Type 2 Diabetes      152.3       81.8
4             Never       Medicaid   Type 2 Diabetes      169.7       65.0
23              NaN        Private   Type 2 Diabetes      173.3       86.9
41          Current       Medicaid   Type 2 Diabetes      166.8       84.6
45          Current        Private   Type 2 Diabetes      151.5       49.1
...             ...            ...               ...        ...        ...
1109          Never        Private   Type 2 Diabetes      162.5       99.2
1117        Current      Uninsured   Type 2 Diabetes      180.3       73.1
1160          Never       Medicare   Type 2 Diabetes      166.3       60.5
1165          Never      Uninsured   Type 2 Diabetes      185.3       77.1
1191         Former        Private   Type 2 Diabetes      180.2       61.0

      systolic_bp  diastolic_bp  heart_rate_bpm last_admission_date
0              71            58              75          2024-07-19
4             117            59              72          2024-11-15
23            120            79              70          2025-04-28
41            127            78              89          2024-02-26
45            120            72              98          2025-05-10
...           ...           ...             ...                 ...
1109          132            86              84          2024-04-16
1117          128            76              78          2025-01-01
1160          104            74              77          2025-09-19
1165          128            75              60          2025-06-24
1191          113            96              64          2024-02-17

[62 rows x 16 columns]

### Groupby on multiple cols

In [148]:
P_record.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [154]:
Group4=P_record.groupby(['first_name','primary_condition', 'smoking_status'])
Group4.size()

first_name  primary_condition    smoking_status
Ahmed       Anxiety Disorder     Current           2
                                 Never             2
            Asthma               Former            1
            Atrial Fibrillation  Current           1
                                 Never             1
                                                  ..
Yuki        Hypothyroidism       Former            1
                                 Never             2
            Obesity              Never             4
            Osteoarthritis       Former            1
                                 Never             1
Length: 691, dtype: int64

In [155]:
Group4.get_group(('Priya', 'Asthma', 'Never'))

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
1075,PT101075,Priya,Davis,Female,20,A+,OH,Never,Medicaid,Asthma,169.2,81.5,131,88,76,2024-03-07

In [157]:
### find all the O+ pateints who have type2  daibetes

Group=P_record.groupby(['gender','blood_type','primary_condition'])
Group.size()

gender  blood_type  primary_condition
Female  A+          Anxiety Disorder          14
                    Asthma                    13
                    Atrial Fibrillation        8
                    COPD                      13
                    Chronic Kidney Disease     5
                                              ..
Other   O+          GERD                       1
                    Hypertension               1
                    Obesity                    1
        O-          Anxiety Disorder           1
                    Chronic Kidney Disease     1
Length: 199, dtype: int64

In [161]:
Group.get_group(('Female', 'O+', 'Type 2 Diabetes'))

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
47,PT100047,Ingrid,Anderson,Female,61,O+,TX,Former,Private,Type 2 Diabetes,163.9,63.7,107,73,88,2023-01-07
133,PT100133,Sarah,Patel,Female,16,O+,IL,Never,Private,Type 2 Diabetes,171.1,87.8,157,90,72,2025-05-21
137,PT100137,William,Miller,Female,47,O+,AZ,Never,Private,Type 2 Diabetes,163.2,85.9,116,83,77,2024-07-21
198,PT100198,Susan,Jackson,Female,92,O+,PA,NaN,Private,Type 2 Diabetes,158.0,73.7,143,89,80,2024-08-28
220,PT100220,Wei,Garcia,Female,80,O+,FL,Never,Private,Type 2 Diabetes,183.5,55.3,95,81,69,2024-05-12
306,PT100306,Noor,Martin,Female,67,O+,NJ,Never,Private,Type 2 Diabetes,165.4,68.9,124,71,74,2024-11-07
311,PT100311,Patricia,Williams,Female,2,O+,PA,Current,Medicare,Type 2 Diabetes,172.6,95.1,134,88,90,2025-08-20
397,PT100397,Thomas,Jackson,Female,53,O+,MA,Never,Private,Type 2 Diabetes,161.8,76.2,111,79,63,2024-09-21
399,PT100399,Omar,Garcia,Female,37,O+,VA,Former,Private,Type 2 Diabetes,176.8,87.6,200,73,70,2024-06-04
455,PT100455,William,Khan,Female,7,O+,TX,Former,Medicaid,Type 2 Diabetes,163.1,87.3,134,78,79,2025-04-21
457,PT100457,Jessica,Lee,Female,74,O+,NC,Current,Private,Type 2 Diabetes,166.4,63.4,103,89,67,2023-03-06
474,PT100474,Sofia,Davis,Female,36,O+,GA,Former,Medicare,Type 2 Diabetes,191.5,116.7,101,104,75,2023-04-29
560,PT100560,Susan,Mueller,Female,87,O+,GA,Former,Medicare,Type 2 Diabetes,183.9,59.8,125,75,78,2025-07-08
627,PT100627,Jennifer,Kim,Female,70,O+,NJ,Former,Private,Type 2 Diabetes,165.9,60.2,153,71,74,2025-01-21
732,PT100732,Wei,Davis,Female,72,O+,MA,Former,Medicaid,Type 2 Diabetes,172.6,81.7,130,48,85,2025-10-31
761,PT100761,Amara,Mueller,Female,84,O+,FL,NaN,Private,Type 2 Diabetes,179.4,NaN,135,99,74,2025-12-26
763,PT100763,Ingrid,Mueller,Female,29,O+,WA,Never,Private,Type 2 Diabetes,163.3,55.0,122,80,69,2025-12-24
777,PT100777,Omar,Smith,Female,28,O+,MI,Never,Private,Type 2 Diabetes,155.9,89.7,136,82,82,2025-06-07
840,PT100840,Robert,Taylor,Female,19,O+,NC,Former,Private,Type 2 Diabetes,175.3,67.4,141,82,85,2024-07-06
887,PT100887,Sofia,Davis,Female,19,O+,NJ,Former,Private,Type 2 Diabetes,175.3,100.3,128,46,71,2024-09-13
900,PT100900,Patricia,Rossi,Female,60,O+,NJ,Never,Medicare,Type 2 Diabetes,173.8,68.9,129,55,57,2025-01-15
1003,PT101003,Barbara,Rodriguez,Female,93,O+,GA,Never,Private,Type 2 Diabetes,150.1,82.4,139,76,59,2023-01-30
1040,PT101040,John,Chen,Female,90,O+,OH,Never,Private,Type 2 Diabetes,164.5,60.3,118,53,96,2024-08-06
1093,PT101093,Mary,Lopez,Female,70,O+,NC,Never,Medicare,Type 2 Diabetes,165.8,55.3,156,67,81,2023-03-04
1109,PT101109,Jennifer,Patel,Female,33,O+,OH,Never,Private,Type 2 Diabetes,162.5,99.2,132,86,84,2024-04-16
1160,PT101160,Richard,Anderson,Female,6,O+,CA,Never,Medicare,Type 2 Diabetes,166.3,60.5,104,74,77,2025-09-19
1191,PT101191,Richard,Mueller,Female,28,O+,VA,Former,Private,Type 2 Diabetes,180.2,61.0,113,96,64,2024-02-17

In [163]:
Group6=P_record.groupby(['gender','smoking_status', 'state'])
Group6.size()

first_name  smoking_status  state
Ahmed       Current         AZ       1
                            FL       5
                            IL       2
                            NC       2
                            TX       1
                                    ..
Yuki        Never           NY       3
                            OH       2
                            PA       1
                            TX       2
                            VA       1
Length: 765, dtype: int64

In [31]:
gender=input('enter the gender')

Sms_key=input('enter the smokin_status')
state_key=input('enter the state')

key = (gender, Sms_key, state_key)

if key in Group6.groups:
    print(Group6.get_group(key))
else:
    print(f"No group found for {key}")

enter the gender Female
enter the smokin_status Current
enter the state VA

NameError: name 'Group6' is not defined

In [2]:
import pandas as pd

P_record=pd.read_csv('patient_records.csv')
P_record

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,27,NaN,AZ,Never,Private,Atrial Fibrillation,177.1,73.5,136,62,87,2025-06-12
1196,PT101196,Joseph,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
1197,PT101197,Patricia,White,Male,52,A+,PA,Current,Private,Chronic Kidney Disease,171.0,66.0,132,94,66,2025-08-01
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [3]:
P_record.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [7]:
## find the top 10 pateints with highest heart rate

P_category=P_record.groupby('first_name')['heart_rate_bpm']
P_category.value_counts()

first_name  heart_rate_bpm
Ahmed       94                4
            73                4
            81                3
            83                3
            65                3
                             ..
Yuki        75                1
            89                1
            86                1
            98                1
            53                1
Name: count, Length: 829, dtype: int64

In [13]:
P_record.groupby('first_name')['heart_rate_bpm'].sum()

first_name
Ahmed        3041
Amara        2693
Barbara      2111
Carlos       1989
Charles      2370
David        2506
Diego        2084
Elena        2746
Elizabeth    3467
Fatima       2438
Hiroshi      2756
Ingrid       2681
James        2859
Jennifer     2736
Jessica      3211
John         2603
Joseph       2635
Karen        2009
Kwame        2003
Linda        2212
Mary         3011
Michael      2751
Noor         2747
Omar         2400
Patricia     2834
Priya        1905
Richard      2511
Robert       3223
Sarah        3241
Sofia        2093
Susan        2866
Thomas       2744
Wei          2744
William      1926
Yuki         2538
Name: heart_rate_bpm, dtype: int64

In [14]:
P_record.groupby('first_name')['heart_rate_bpm'].sum().sort_values(ascending=False)

first_name
Elizabeth    3467
Sarah        3241
Robert       3223
Jessica      3211
Ahmed        3041
Mary         3011
Susan        2866
James        2859
Patricia     2834
Hiroshi      2756
Michael      2751
Noor         2747
Elena        2746
Thomas       2744
Wei          2744
Jennifer     2736
Amara        2693
Ingrid       2681
Joseph       2635
John         2603
Yuki         2538
Richard      2511
David        2506
Fatima       2438
Omar         2400
Charles      2370
Linda        2212
Barbara      2111
Sofia        2093
Diego        2084
Karen        2009
Kwame        2003
Carlos       1989
William      1926
Priya        1905
Name: heart_rate_bpm, dtype: int64

In [16]:
P_record.groupby('first_name')['heart_rate_bpm'].sum().sort_values(ascending=False).head(10)

first_name
Elizabeth    3467
Sarah        3241
Robert       3223
Jessica      3211
Ahmed        3041
Mary         3011
Susan        2866
James        2859
Patricia     2834
Hiroshi      2756
Name: heart_rate_bpm, dtype: int64

In [17]:
P_record.groupby('first_name')['heart_rate_bpm'].sum().sort_values(ascending=False).head(1).index[0]

'Elizabeth'

In [18]:
P_record.groupby('first_name')['heart_rate_bpm'].count()

first_name
Ahmed        39
Amara        36
Barbara      29
Carlos       26
Charles      32
David        33
Diego        29
Elena        37
Elizabeth    48
Fatima       31
Hiroshi      36
Ingrid       35
James        37
Jennifer     38
Jessica      43
John         35
Joseph       34
Karen        26
Kwame        27
Linda        30
Mary         40
Michael      36
Noor         36
Omar         32
Patricia     37
Priya        25
Richard      34
Robert       43
Sarah        42
Sofia        27
Susan        35
Thomas       37
Wei          35
William      25
Yuki         35
Name: heart_rate_bpm, dtype: int64

In [23]:
P_T=P_record.groupby(['first_name','primary_condition', 'weight_kg']).sum()
P_T

                                       patient_id last_name  gender  age  \
first_name primary_condition weight_kg
Ahmed      Anxiety Disorder  47.4        PT100452       Kim    Male   10
                             54.0        PT100748  Martinez    Male   94
                             63.0        PT100381  Gonzalez    Male   88
                             79.6        PT100477     Rossi    Male   88
           Asthma            76.0        PT100015     Davis  Female   46
...                                           ...       ...     ...  ...
Yuki       Obesity           75.5        PT100256     Jones    Male    5
                             85.9        PT100625     Perez  Female   59
                             95.9        PT100336    Taylor  Female   54
           Osteoarthritis    70.8        PT100663     White  Female   12
                             79.3        PT100462    Martin    Male   79

                                       blood_type state smoking_status  \
first_name primary_condition weight_kg
Ahmed      Anxiety Disorder  47.4              B+    NJ          Never
                             54.0              A-    NY          Never
                             63.0              O-    FL        Current
                             79.6              A+    FL        Current
           Asthma            76.0              O+    NY         Former
...                                           ...   ...            ...
Yuki       Obesity           75.5              O-    TX          Never
                             85.9                    NY
                             95.9              A-    OH          Never
           Osteoarthritis    70.8                    CA         Former
                             79.3              B-    NC          Never

                                       insurance_type  height_cm  systolic_bp  \
first_name primary_condition weight_kg
Ahmed      Anxiety Disorder  47.4             Private      149.2          110
                             54.0            Medicare      191.5          129
                             63.0            Medicaid      166.6          133
                             79.6             Private      167.4          120
           Asthma            76.0             Private      184.6          131
...                                               ...        ...          ...
Yuki       Obesity           75.5             Private      176.5          138
                             85.9             Private      158.0          124
                             95.9            Medicare      162.4          148
           Osteoarthritis    70.8            Medicaid      180.5          129
                             79.3             Private      174.3          118

                                        diastolic_bp  heart_rate_bpm  \
first_name primary_condition weight_kg
Ahmed      Anxiety Disorder  47.4                 82              81
                             54.0                 82              77
                             63.0                 78              94
                             79.6                 85              71
           Asthma            76.0                 79              73
...                                              ...             ...
Yuki       Obesity           75.5                 84              85
                             85.9                 75              72
                             95.9                103              79
           Osteoarthritis    70.8                 76              62
                             79.3                 81              63

                                       last_admission_date
first_name primary_condition weight_kg
Ahmed      Anxiety Disorder  47.4               2024-01-10
                             54.0               2023-12-19
                             63.0               2024-04-12
                             79.6               2023-02-22
           Asthma            76.0               2023-06-28
...                                                    ...
Yuki       Obesity           75.5               2023-05-25
                             85.9               2025-12-12
                             95.9               2025-03-17
           Osteoarthritis    70.8               2025-08-28
                             79.3               2025-03-05

[1145 rows x 13 columns]

In [25]:
P_T=P_record.groupby(['primary_condition', 'weight_kg'])['first_name'].sum()
P_T

primary_condition  weight_kg
Anxiety Disorder   34.4         Jennifer
                   45.6          Jessica
                   47.4            Ahmed
                   51.5          Richard
                   53.3             Mary
                                  ...
Type 2 Diabetes    104.4           Priya
                   106.1            Omar
                   113.4          Joseph
                   116.7           Sofia
                   116.9            John
Name: first_name, Length: 1061, dtype: str

In [27]:
P_record['weight_kg'].sort_values(ascending=False)

1171    126.2
643     125.0
108     123.7
1072    123.5
201     118.1
        ...
1120      NaN
1127      NaN
1180      NaN
1186      NaN
1198      NaN
Name: weight_kg, Length: 1200, dtype: float64

In [32]:

primary_condition=input('enter the problem')
weight_key=input('enter the weight')


key = (primary_condition, weight_key)

if key in P_T.groups:
    print(P_T.get_group(key))
else:
    print(f"No group found for {key}")

enter the problem Type 2 Daibetes
enter the weight 125

AttributeError: 'Series' object has no attribute 'groups'

In [36]:
df_weight=P_record[P_record['weight_kg']>80]
df_weight[(df_weight['primary_condition']=='Type 2 Diabetes')]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
23,PT100023,Amara,Rodriguez,Male,78,O+,VA,NaN,Private,Type 2 Diabetes,173.3,86.9,120,79,70,2025-04-28
41,PT100041,Omar,Patel,Male,0,O+,FL,Current,Medicaid,Type 2 Diabetes,166.8,84.6,127,78,89,2024-02-26
56,PT100056,Karen,Gonzalez,Female,79,A+,WA,Former,Private,Type 2 Diabetes,166.5,91.9,137,71,73,2024-12-08
80,PT100080,Joseph,Perez,Male,61,AB-,MA,Never,Private,Type 2 Diabetes,182.5,87.0,137,74,92,2023-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,PT101038,Barbara,Martinez,Female,88,B+,OH,Never,Private,Type 2 Diabetes,NaN,97.6,108,101,52,2023-09-23
1058,PT101058,David,Anderson,Male,79,NaN,PA,Never,Private,Type 2 Diabetes,157.8,92.8,114,83,84,2023-10-01
1109,PT101109,Jennifer,Patel,Female,33,O+,OH,Never,Private,Type 2 Diabetes,162.5,99.2,132,86,84,2024-04-16
1115,PT101115,Jennifer,Mueller,Female,92,A+,NY,Never,Private,Type 2 Diabetes,153.5,88.2,155,100,56,2023-03-24
1131,PT101131,Amara,Wilson,Male,6,A+,NY,Former,Medicaid,Type 2 Diabetes,187.9,81.9,151,96,85,2023-09-21

In [44]:
df_weight.groupby('first_name')['age'].count()

first_name
Ahmed        10
Amara         9
Barbara      15
Carlos        7
Charles      11
David        11
Diego        10
Elena        17
Elizabeth    21
Fatima       10
Hiroshi      11
Ingrid       12
James         6
Jennifer     13
Jessica      17
John         12
Joseph       15
Karen        10
Kwame        15
Linda         6
Mary         11
Michael      19
Noor         13
Omar         14
Patricia     15
Priya        12
Richard       9
Robert       11
Sarah        14
Sofia        14
Susan         8
Thomas       16
Wei          12
William      10
Yuki         10
Name: age, dtype: int64

In [51]:

df_person=P_record[(P_record['first_name']=='Priya') & (P_record['age']<20)] 

df_person

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
510,PT100510,Priya,Smith,Female,10,O-,IL,Current,Medicaid,Hypothyroidism,166.9,83.0,114,76,62,2025-11-17
545,PT100545,Priya,Anderson,Female,10,A+,PA,Never,Private,COPD,148.6,97.9,170,78,75,2024-02-01
678,PT100678,Priya,Khan,Female,19,B+,FL,NaN,Private,Type 2 Diabetes,160.5,104.4,129,66,82,2023-07-04
948,PT100948,Priya,Rodriguez,Male,11,AB+,PA,Current,Uninsured,Anxiety Disorder,163.1,82.9,121,88,98,2023-03-26
1116,PT101116,Priya,Anderson,Female,16,A+,IL,Former,Private,COPD,167.4,85.0,103,71,83,2024-04-06
1128,PT101128,Priya,Smith,Male,17,B+,GA,Former,Private,Coronary Artery Disease,162.9,66.9,108,90,87,2025-11-27

In [60]:
## creating a function which can give the age of pateint if primary condition is Anxiety Disorder

P_cat=P_record[P_record['primary_condition']=='Anxiety Disorder']
P_cat.groupby('patient_id')['age'].sum()

def age(primary_condition):
    P_cat=P_record[P_record['primary_condition']=='Anxiety Disorder']
    return P_cat.groupby('patient_id')['age'].sum().sort_values(ascending=False).head(1)

In [61]:
age('Anxiety Disorder')

patient_id
PT100216    94
Name: age, dtype: int64

###  Questions

In [62]:
### What is the average billed_amount for each claim_type in the insurance claims data?

import pandas as pd
import numpy as np

I_C=pd.read_csv('insurance_claims.csv')
I_C.head()

,claim_id,patient_id,claim_date,diagnosis_code,diagnosis_description,claim_type,provider_npi,billed_amount,claim_status,approved_amount,payer
0,CLM500000,PT100636,2024-04-20,I25.10,Coronary artery disease,Prescription,1000000079,59.13,Approved,53.95,Aetna
1,CLM500001,PT100923,2023-07-17,M54.5,Low back pain,Lab Work,1000000105,67.59,Approved,67.22,Medicare
2,CLM500002,PT101142,2025-04-06,F41.1,Generalized Anxiety Disorder,Outpatient Visit,1000000166,224.00,Pending,NaN,Medicare
3,CLM500003,PT100710,2023-05-11,N39.0,Urinary tract infection,Emergency Room,1000000195,2557.82,Approved,2188.41,Medicaid
4,CLM500004,PT101087,2023-01-25,F41.1,Generalized Anxiety Disorder,Inpatient Stay,1000000020,7707.24,Approved,6572.36,Cigna

In [63]:
I_C.groupby('claim_type')['billed_amount'].mean()

claim_type
Diagnostic Imaging           656.688571
Emergency Room              1370.042813
Inpatient Stay              9161.576599
Lab Work                      92.114545
Outpatient Visit             181.138000
Physical Therapy             115.282981
Prescription                  59.836623
Specialist Consultation      253.227178
Surgery                    14922.596129
Name: billed_amount, dtype: float64

In [69]:
#### How many patients fall into each primary_condition category?

I_C.groupby('diagnosis_description')['patient_id'].value_counts()

diagnosis_description              patient_id
Acute upper respiratory infection  PT100063      3
                                   PT100207      2
                                   PT100628      2
                                   PT100005      2
                                   PT100398      2
                                                ..
Urinary tract infection            PT100898      1
                                   PT100214      1
                                   PT100335      1
                                   PT100348      1
                                   PT100863      1
Name: count, Length: 2675, dtype: int64

In [70]:
P_record=pd.read_csv('patient_records.csv')
P_record.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [73]:
###   What is the minimum, maximum, and average heart_rate_bpm for each smoking_status group?

P_category=P_record.groupby('smoking_status')['heart_rate_bpm']
P_category.agg(['min', 'max', 'mean'])

                min  max       mean
smoking_status
Current          44  102  76.186047
Former           28  107  75.480712
Never            34  112  75.331768

In [74]:
## For each test_name in the lab results, compute the mean, min, 
## and max result_value in a single groupby call using

P_LR=pd.read_csv('lab_results.csv')
P_LR.head(2)

,lab_id,patient_id,test_name,result_value,reference_range_low,reference_range_high,flag,test_date,ordering_facility
0,LAB300000,PT101182,ALT (U/L),13.30,7.0,56.0,Normal,2024-09-20,Northside Clinic Lab
1,LAB300001,PT100847,Hemoglobin (g/dL),10.59,12.0,17.5,Low,2023-04-22,Northside Clinic Lab

In [77]:
P_Lab=P_LR.groupby('test_name')['result_value'].agg(['min', 'max', 'mean'])
P_Lab

                                    min     max        mean
test_name
ALT (U/L)                          0.10   60.81   27.036576
Creatinine (mg/dL)                 0.21    1.86    0.973892
Fasting Glucose (mg/dL)           25.05  195.14   95.456675
HDL Cholesterol (mg/dL)            6.49   81.49   51.773575
Hemoglobin (g/dL)                  8.75   17.73   13.393981
Hemoglobin A1c (%)                 2.55    8.80    5.774949
LDL Cholesterol (mg/dL)           39.77  177.87  111.998550
TSH (mIU/L)                        0.10    6.55    2.493494
Total Cholesterol (mg/dL)         64.13  266.83  185.898472
White Blood Cell Count (x10^9/L)   1.18   12.93    6.796070

In [79]:
I_C.head(2)

,claim_id,patient_id,claim_date,diagnosis_code,diagnosis_description,claim_type,provider_npi,billed_amount,claim_status,approved_amount,payer
0,CLM500000,PT100636,2024-04-20,I25.10,Coronary artery disease,Prescription,1000000079,59.13,Approved,53.95,Aetna
1,CLM500001,PT100923,2023-07-17,M54.5,Low back pain,Lab Work,1000000105,67.59,Approved,67.22,Medicare

In [86]:
## For each payer in the insurance claims, find the total 
## billed_amount, total approved_amount, and the count of claims 
##— all in one .agg() call with custom output column names.

result=I_C.groupby('payer').agg(total_bill=('billed_amount', 'sum'), total_approved=('approved_amount', 'sum'), total_claims=('claim_id', 'count'))
result

                      total_bill  total_approved  total_claims
payer
Aetna                  556981.24       396594.24           469
BlueCross BlueShield   636550.03       441190.30           498
Cigna                  599953.33       422400.44           491
Medicaid               812209.19       499935.98           533
Medicare               660670.04       473771.30           499
UnitedHealthcare       465028.01       329821.68           510

In [87]:
## Group disease_outbreak.csv by both disease and region — what is the average weekly reported_cases for each disease/region combination? 
## Which region has the highest average for COVID-19 specifically?

P_DO=pd.read_csv('E:\\codedisease_outbreak.csv')
P_DO.head(2)

,disease,region,week_start_date,reported_cases,hospitalizations,deaths
0,Influenza A,Northeast,2024-01-01,95,9,0
1,Influenza A,Northeast,2024-01-08,93,2,0

In [89]:
Dise_o=P_DO.groupby(['disease', 'region'])['reported_cases'].mean()
Dise_o

disease      region
COVID-19     Midwest      167.085714
             Northeast    117.038095
             Southeast    189.961905
             Southwest    286.390476
             West         242.761905
Influenza A  Midwest       35.409524
             Northeast     44.980952
             Southeast     19.990476
             Southwest     49.819048
             West          46.600000
Measles      Midwest      198.961905
             Northeast    491.466667
             Southeast    358.000000
             Southwest    232.609524
             West         263.809524
Norovirus    Midwest      254.609524
             Northeast    126.085714
             Southeast    149.742857
             Southwest    167.923810
             West         115.838095
Pertussis    Midwest      122.847619
             Northeast    224.228571
             Southeast    172.142857
             Southwest    138.085714
             West         141.819048
RSV          Midwest      216.885714
             Northeast    195.504762
             Southeast    271.885714
             Southwest    257.228571
             West         244.400000
Name: reported_cases, dtype: float64

In [90]:
## . Group lab_results.csv by test_name and flag — how many "High," "Low," and "Normal" results exist for each test?

P_LR.head(2)

,lab_id,patient_id,test_name,result_value,reference_range_low,reference_range_high,flag,test_date,ordering_facility
0,LAB300000,PT101182,ALT (U/L),13.30,7.0,56.0,Normal,2024-09-20,Northside Clinic Lab
1,LAB300001,PT100847,Hemoglobin (g/dL),10.59,12.0,17.5,Low,2023-04-22,Northside Clinic Lab

In [91]:
lab_res=P_LR.groupby('test_name')['flag'].value_counts()
lab_res

test_name                         flag
ALT (U/L)                         Normal    386
                                  Low        12
                                  High        5
Creatinine (mg/dL)                Normal    319
                                  High       60
                                  Low        45
Fasting Glucose (mg/dL)           Normal    187
                                  High      173
                                  Low        46
HDL Cholesterol (mg/dL)           Normal    343
                                  Low        57
Hemoglobin (g/dL)                 Normal    354
                                  Low        72
                                  High        1
Hemoglobin A1c (%)                High      206
                                  Normal    162
                                  Low        24
LDL Cholesterol (mg/dL)           High      259
                                  Normal    134
TSH (mIU/L)                       Normal    303
                                  High       60
                                  Low        32
Total Cholesterol (mg/dL)         Normal    254
                                  High      132
White Blood Cell Count (x10^9/L)  Normal    339
                                  Low        30
                                  High        5
Name: count, dtype: int64

In [92]:
###  Which 5 radiologist_ids reviewed the most imaging studies? 
##(Hint: groupby().size().sort_values(ascending=False).head())

P_scan=pd.read_csv('E:\\code\\imaging.csv')
P_scan.head(2)

,image_id,patient_id,modality,body_part,study_date,radiologist_id,finding_summary,file_size_mb,image_resolution,contrast_used
0,IMG400000,PT100779,MRI,Spine,2023-07-16,RAD025,Nodule - recommend follow-up,278.3,512x512,False
1,IMG400001,PT100870,X-Ray,Hand,2024-07-06,RAD014,Nodule - recommend follow-up,1.5,2048x2048,False

In [94]:
image=P_scan.groupby('radiologist_id')['modality'].size().sort_values(ascending=False).head(5)
image

radiologist_id
RAD004    106
RAD025    103
RAD005    102
RAD009     98
RAD011     97
Name: modality, dtype: int64

In [98]:
### Using groupby().filter(), find only the claim_type groups 
## where the average billed_amount exceeds $1,000.

I_C.head(2)

,claim_id,patient_id,claim_date,diagnosis_code,diagnosis_description,claim_type,provider_npi,billed_amount,claim_status,approved_amount,payer
0,CLM500000,PT100636,2024-04-20,I25.10,Coronary artery disease,Prescription,1000000079,59.13,Approved,53.95,Aetna
1,CLM500001,PT100923,2023-07-17,M54.5,Low back pain,Lab Work,1000000105,67.59,Approved,67.22,Medicare

In [102]:
Insurance=I_C.groupby('claim_type')['billed_amount'].mean()>1000
Insurance

claim_type
Diagnostic Imaging         False
Emergency Room              True
Inpatient Stay              True
Lab Work                   False
Outpatient Visit           False
Physical Therapy           False
Prescription               False
Specialist Consultation    False
Surgery                     True
Name: billed_amount, dtype: bool

In [109]:
I_C['billed_amount'].mean()

np.float64(1243.79728)

In [108]:
Insurance=I_C.groupby('claim_type').filter(lambda x: x['billed_amount'].mean()>1000)
Insurance

,claim_id,patient_id,claim_date,diagnosis_code,diagnosis_description,claim_type,provider_npi,billed_amount,claim_status,approved_amount,payer
3,CLM500003,PT100710,2023-05-11,N39.0,Urinary tract infection,Emergency Room,1000000195,2557.82,Approved,2188.41,Medicaid
4,CLM500004,PT101087,2023-01-25,F41.1,Generalized Anxiety Disorder,Inpatient Stay,1000000020,7707.24,Approved,6572.36,Cigna
9,CLM500009,PT100356,2025-01-27,J06.9,Acute upper respiratory infection,Inpatient Stay,1000000182,8923.04,Denied,0.00,BlueCross BlueShield
10,CLM500010,PT100606,2023-03-24,E11.9,Type 2 Diabetes without complications,Emergency Room,1000000044,842.49,Approved,814.92,Aetna
19,CLM500019,PT100825,2025-11-08,I10,Essential Hypertension,Emergency Room,1000000068,939.61,Partially Approved,496.41,Medicaid
...,...,...,...,...,...,...,...,...,...,...,...
2992,CLM502992,PT100254,2025-08-01,F32.9,Major Depressive Disorder,Surgery,1000000161,5785.29,Approved,5259.95,BlueCross BlueShield
2993,CLM502993,PT100836,2024-12-14,F32.9,Major Depressive Disorder,Emergency Room,1000000058,1767.51,Approved,1566.52,Medicare
2995,CLM502995,PT100760,2023-05-22,E11.9,Type 2 Diabetes without complications,Surgery,1000000142,14316.32,Approved,12628.64,Cigna
2996,CLM502996,PT100009,2024-11-07,E11.9,Type 2 Diabetes without complications,Emergency Room,1000000008,327.97,Approved,283.83,Medicaid
2999,CLM502999,PT100664,2023-05-26,M17.9,Osteoarthritis of knee,Inpatient Stay,1000000024,7720.20,Pending,NaN,Medicaid

In [105]:
Insurance.value_counts()

billed_amount
False    6
True     3
Name: count, dtype: int64

In [110]:
## For each patient, calculate how their weight_kg compares to the average weight of patients with 
## the same primary_condition (i.e., their weight minus the group average). Use groupby().transform().

P_record.head(1)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19