In [3]:
import pandas as pd
import numpy as np

In [5]:
## vectorise operations handle the functions upon strings, excludes the none values and doesnt lead to code crash

### for example

s=pd.Series(['cat', 'mat', None, 'rat'])
[i.startswith['c'] for i in s]           ### throws the error

TypeError: 'builtin_function_or_method' object is not subscriptable

In [6]:
###  now pandas solved this thing by following

s=pd.Series(['cat', 'mat', None, 'rat'])

### string accesor
s.str.startswith('c')     ### gives the false in place of 'None'

0     True
1    False
2    False
3    False
dtype: bool

In [4]:
P_record=pd.read_csv('E:\\code\\patient_records.csv')
P_record.head(1)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19

In [5]:
## making all the last name into lowercases

P_record['last_name'].str.lower()

0         jackson
1           smith
2          nguyen
3           brown
4           rossi
          ...
1195        silva
1196    rodriguez
1197        white
1198         chen
1199     thompson
Name: last_name, Length: 1200, dtype: str

In [6]:
P_record['last_name'].str.capitalize()

0         Jackson
1           Smith
2          Nguyen
3           Brown
4           Rossi
          ...
1195        Silva
1196    Rodriguez
1197        White
1198         Chen
1199     Thompson
Name: last_name, Length: 1200, dtype: str

In [7]:
P_record['last_name'].str.title()

0         Jackson
1           Smith
2          Nguyen
3           Brown
4           Rossi
          ...
1195        Silva
1196    Rodriguez
1197        White
1198         Chen
1199     Thompson
Name: last_name, Length: 1200, dtype: str

In [8]:
P_record['first_name'].str.len()

0       5
1       7
2       4
3       6
4       5
       ..
1195    9
1196    6
1197    8
1198    4
1199    5
Name: first_name, Length: 1200, dtype: int64

In [14]:
P_record['first_name'][P_record['first_name'].str.len()]

5       Karen
7    Jennifer
4       Priya
6       Karen
5       Karen
       ...
9        John
6       Karen
8       Sarah
4       Priya
5       Karen
Name: first_name, Length: 1200, dtype: str

In [19]:
P_record['first_name'][P_record['first_name'].str.len()].values[2]

'Priya'

### strip function------> to skip the white spaces

In [20]:
P_record['first_name'].str.strip()

0           Sarah
1         Jessica
2            John
3          Robert
4           Priya
          ...
1195    Elizabeth
1196       Joseph
1197     Patricia
1198         John
1199        Susan
Name: first_name, Length: 1200, dtype: str

In [21]:
P_record.head()

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
4,PT100004,Priya,Rossi,Female,36,O+,AZ,Never,Medicaid,Type 2 Diabetes,169.7,65.0,117,59,72,2024-11-15

In [34]:
### filtering

P_record[P_record['first_name'].str.startswith('A')]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
15,PT100015,Ahmed,Davis,Female,46,O+,NY,Former,Private,Asthma,184.6,76.0,131,79,73,2023-06-28
23,PT100023,Amara,Rodriguez,Male,78,O+,VA,NaN,Private,Type 2 Diabetes,173.3,86.9,120,79,70,2025-04-28
38,PT100038,Amara,Smith,Female,80,O+,TX,Never,Medicare,Anxiety Disorder,150.2,63.6,133,94,75,2023-02-18
49,PT100049,Ahmed,Smith,Female,16,O+,MI,Never,Medicaid,Depression,173.3,76.5,128,98,67,2025-10-18
105,PT100105,Ahmed,Thompson,Male,10,B+,WA,Former,Private,Type 2 Diabetes,180.7,76.3,129,82,54,2025-03-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,PT101114,Amara,Khan,Other,24,B-,GA,Former,Private,Coronary Artery Disease,167.0,84.4,127,78,72,2023-04-04
1131,PT101131,Amara,Wilson,Male,6,A+,NY,Former,Medicaid,Type 2 Diabetes,187.9,81.9,151,96,85,2023-09-21
1141,PT101141,Amara,Taylor,Male,55,A+,NY,Never,Private,Hypertension,174.4,50.4,131,92,80,2024-02-27
1176,PT101176,Ahmed,Martinez,Female,61,O+,NJ,Former,Private,Hypertension,173.2,53.4,102,84,86,2024-08-08
1183,PT101183,Amara,Rodriguez,Female,29,O+,GA,Never,Private,Osteoarthritis,146.6,88.1,114,63,62,2025-01-23

In [36]:
### endswith

P_record[P_record['last_name'].str.startswith('A')]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
24,PT100024,Noor,Anderson,Male,33,O+,MA,Never,Private,GERD,185.6,62.0,106,66,62,2025-01-22
47,PT100047,Ingrid,Anderson,Female,61,O+,TX,Former,Private,Type 2 Diabetes,163.9,63.7,107,73,88,2023-01-07
70,PT100070,Richard,Anderson,Female,84,A-,NC,Never,VA,Hypertension,183.3,80.5,116,76,75,2023-10-19
147,PT100147,Michael,Anderson,Male,55,O-,FL,Former,Medicaid,Coronary Artery Disease,181.5,74.0,147,82,64,2023-08-16
153,PT100153,Wei,Anderson,Male,18,O-,PA,Never,Private,Hypertension,183.9,67.9,127,45,74,2023-08-18
181,PT100181,John,Anderson,Male,43,B+,PA,Never,Private,Hypothyroidism,154.7,74.0,108,85,77,2023-12-09
212,PT100212,David,Anderson,Female,17,A+,NY,Former,Medicaid,Depression,169.0,66.1,123,87,81,2023-02-03
214,PT100214,James,Anderson,Male,9,B+,WA,Never,Private,Hypertension,179.9,103.2,133,76,83,2024-06-05
218,PT100218,Noor,Anderson,Male,62,O+,TX,Never,Private,Asthma,142.7,72.7,144,68,73,2023-06-24
239,PT100239,James,Anderson,Female,80,O+,IL,Never,Private,Osteoarthritis,174.9,79.2,138,71,74,2024-09-16
302,PT100302,William,Anderson,Male,21,O+,MI,Never,Medicare,Anxiety Disorder,178.8,90.9,128,68,83,2025-11-30
309,PT100309,Joseph,Anderson,Female,83,A+,GA,Never,Private,Obesity,167.5,71.1,125,76,79,2024-12-25
373,PT100373,Hiroshi,Anderson,Female,67,A+,NC,Never,Private,COPD,165.1,77.3,104,80,83,2024-09-14
417,PT100417,Mary,Anderson,Male,82,O-,NC,Former,Medicare,Obesity,179.5,77.3,106,96,84,2024-04-14
545,PT100545,Priya,Anderson,Female,10,A+,PA,Never,Private,COPD,148.6,97.9,170,78,75,2024-02-01
573,PT100573,Sarah,Anderson,Male,93,A+,FL,Never,Private,Coronary Artery Disease,161.4,88.0,107,62,78,2023-03-18
578,PT100578,Susan,Anderson,Male,26,A+,CA,Former,Private,Coronary Artery Disease,161.2,56.3,111,85,90,2023-04-25
620,PT100620,Ingrid,Anderson,Male,33,A+,CA,Former,Medicaid,Type 2 Diabetes,157.6,NaN,171,82,77,2024-08-17
708,PT100708,Kwame,Anderson,Female,85,O+,MI,Never,Medicare,Atrial Fibrillation,178.7,87.0,145,73,73,2023-08-02
726,PT100726,Jessica,Anderson,Female,79,O-,NY,Current,Private,Osteoarthritis,174.3,83.4,118,92,73,2024-01-11
811,PT100811,Hiroshi,Anderson,Female,26,O+,MA,Never,Medicare,Depression,174.6,66.1,126,69,74,2025-03-06
907,PT100907,Elizabeth,Anderson,Female,12,A+,NY,Current,Private,Hypertension,177.6,70.8,127,57,63,2023-10-03
920,PT100920,Noor,Anderson,Female,8,O+,VA,Never,Medicare,Anxiety Disorder,151.2,69.0,148,87,74,2024-05-29
937,PT100937,Yuki,Anderson,Female,4,O+,MI,Former,Private,Asthma,180.3,NaN,128,72,80,2023-05-21
954,PT100954,Elizabeth,Anderson,Male,92,O+,NC,Never,Private,Hypertension,149.2,52.4,100,65,81,2024-04-26
1018,PT101018,Diego,Anderson,Female,9,B+,PA,Never,Private,Anxiety Disorder,170.3,61.5,110,79,79,2025-04-19
1034,PT101034,Diego,Anderson,Female,22,O+,FL,Never,Medicaid,Coronary Artery Disease,166.8,NaN,123,90,76,2025-08-24
1058,PT101058,David,Anderson,Male,79,NaN,PA,Never,Private,Type 2 Diabetes,157.8,92.8,114,83,84,2023-10-01
1061,PT101061,Elizabeth,Anderson,Male,89,O+,MI,Former,Medicare,Coronary Artery Disease,164.8,NaN,109,71,65,2025-12-22
1062,PT101062,Joseph,Anderson,Female,82,A-,WA,Never,Private,Osteoarthritis,162.4,77.7,140,94,73,2024-12-02
1116,PT101116,Priya,Anderson,Female,16,A+,IL,Former,Private,COPD,167.4,85.0,103,71,83,2024-04-06
1123,PT101123,Richard,Anderson,Female,16,O+,MA,Never,Private,Asthma,172.4,61.3,113,81,54,2023-06-20
1126,PT101126,Charles,Anderson,Male,12,O+,NJ,Never,Medicare,Anxiety Disorder,151.5,83.3,124,85,62,2023-06-23
1160,PT101160,Richard,Anderson,Female,6,O+,CA,Never,Medicare,Type 2 Diabetes,166.3,60.5,104,74,77,2025-09-19
1163,PT101163,Wei,Anderson,Female,75,O+,IL,Never,Uninsured,Obesity,178.2,81.4,131,68,69,2024-08-13

In [44]:
### advance level filtering

### finding a particular name starts or endswith vowels

P_record['last_name'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')   ### specifically used

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: last_name, Length: 1200, dtype: bool

In [45]:
P_record['last_name'].str.contains('^[^aeiouAEIOU].+[^aeiouAEIOU]$')   ### specifically used

0        True
1        True
2        True
3        True
4       False
        ...
1195    False
1196     True
1197    False
1198     True
1199     True
Name: last_name, Length: 1200, dtype: bool

In [46]:
P_record[P_record['last_name'].str.contains('^[^aeiouAEIOU].+[^aeiouAEIOU]$')]   ### specifically used

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16
2,PT100002,John,Nguyen,Male,70,A+,PA,Never,Private,Asthma,178.1,66.5,104,71,66,2023-10-11
3,PT100003,Robert,Brown,Male,52,O+,PA,Former,Medicare,Chronic Kidney Disease,171.5,NaN,147,77,99,2023-08-09
5,PT100005,Karen,Rodriguez,Male,78,O+,NY,Former,Medicaid,Depression,181.8,100.9,115,69,76,2024-02-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,PT101193,David,Jones,Male,54,O+,FL,Former,Private,Asthma,168.0,70.2,115,83,66,2024-09-27
1194,PT101194,Diego,Wilson,Male,23,O+,AZ,Never,Private,Coronary Artery Disease,177.5,70.6,117,57,87,2025-10-22
1196,PT101196,Joseph,Rodriguez,Female,32,O+,NY,Never,Private,Osteoarthritis,175.9,83.8,146,73,102,2023-03-11
1198,PT101198,John,Chen,Female,27,O-,CA,Never,Medicare,GERD,175.2,NaN,157,71,94,2024-01-27
1199,PT101199,Susan,Thompson,Male,59,A+,IL,Never,Private,Depression,181.7,81.9,112,70,94,2025-06-15

In [38]:
P_record['first_name'].str.contains('Ahmed')

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: first_name, Length: 1200, dtype: bool

In [39]:
P_record[P_record['first_name'].str.contains('Ahmed')]

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
15,PT100015,Ahmed,Davis,Female,46,O+,NY,Former,Private,Asthma,184.6,76.0,131,79,73,2023-06-28
49,PT100049,Ahmed,Smith,Female,16,O+,MI,Never,Medicaid,Depression,173.3,76.5,128,98,67,2025-10-18
105,PT100105,Ahmed,Thompson,Male,10,B+,WA,Former,Private,Type 2 Diabetes,180.7,76.3,129,82,54,2025-03-29
128,PT100128,Ahmed,Kowalski,Female,8,A+,VA,Former,Medicaid,Hypertension,165.8,111.0,119,78,83,2023-11-19
159,PT100159,Ahmed,Thomas,Male,55,O+,VA,Never,Medicaid,Atrial Fibrillation,179.5,82.2,121,73,91,2025-12-29
176,PT100176,Ahmed,Lopez,Female,25,B-,IL,Current,Medicaid,Osteoarthritis,164.6,67.5,104,63,81,2024-11-16
205,PT100205,Ahmed,Rossi,Female,71,O+,AZ,Never,Medicare,Depression,177.0,83.4,127,54,94,2023-05-04
207,PT100207,Ahmed,Jones,Male,24,A+,GA,Never,Private,Osteoarthritis,152.0,65.6,116,70,107,2024-11-16
270,PT100270,Ahmed,Lee,Female,75,O+,AZ,Current,Uninsured,Coronary Artery Disease,176.9,52.6,103,98,79,2024-02-17
308,PT100308,Ahmed,Thomas,Female,69,A-,CA,Former,Medicaid,Obesity,163.5,62.1,154,57,65,2023-09-08
330,PT100330,Ahmed,Patel,Male,91,A+,TX,Current,Medicaid,Depression,172.0,74.4,125,57,65,2025-04-07
381,PT100381,Ahmed,Gonzalez,Male,88,O-,FL,Current,Medicaid,Anxiety Disorder,166.6,63.0,133,78,94,2024-04-12
410,PT100410,Ahmed,Martinez,Male,48,O-,WA,Former,Medicaid,Coronary Artery Disease,170.6,49.9,127,98,73,2024-04-15
419,PT100419,Ahmed,Patel,Male,67,A-,FL,Current,Medicare,Osteoarthritis,163.6,79.8,137,68,70,2025-02-15
452,PT100452,Ahmed,Kim,Male,10,B+,NJ,Never,Private,Anxiety Disorder,149.2,47.4,110,82,81,2024-01-10
477,PT100477,Ahmed,Rossi,Male,88,A+,FL,Current,Private,Anxiety Disorder,167.4,79.6,120,85,71,2023-02-22
501,PT100501,Ahmed,Rossi,Male,76,O+,FL,Former,Private,Coronary Artery Disease,170.0,75.7,137,77,49,2025-08-25
531,PT100531,Ahmed,Lopez,Male,63,B+,NY,Never,Uninsured,Obesity,149.3,96.6,118,44,82,2025-02-01
569,PT100569,Ahmed,Kowalski,Male,60,O+,IL,Never,Medicaid,Hypertension,162.9,50.2,145,88,75,2024-04-05
584,PT100584,Ahmed,Rossi,Male,68,A+,IL,Current,VA,Type 2 Diabetes,176.8,51.3,110,62,67,2023-09-22
604,PT100604,Ahmed,White,Male,66,O+,NC,Current,Medicaid,Atrial Fibrillation,159.4,64.2,101,87,83,2025-07-02
610,PT100610,Ahmed,Perez,Male,35,O+,MI,Former,Medicare,Depression,159.5,NaN,125,90,66,2023-04-08
615,PT100615,Ahmed,Patel,Male,43,A+,WA,Former,Private,Osteoarthritis,149.9,88.8,125,92,83,2025-07-08
623,PT100623,Ahmed,Martin,Female,18,A+,NC,Former,Medicaid,Migraine,152.8,69.8,176,86,81,2024-08-25
652,PT100652,Ahmed,Lopez,Male,71,NaN,NC,Never,Medicaid,Hypertension,156.6,61.4,110,70,73,2025-04-23
653,PT100653,Ahmed,Rodriguez,Female,33,O+,VA,Never,Private,GERD,155.2,77.6,151,72,71,2024-12-13
668,PT100668,Ahmed,Thompson,Female,14,O+,FL,Never,Private,COPD,164.5,83.0,127,77,94,2025-04-01
718,PT100718,Ahmed,Rodriguez,Male,2,O+,FL,Current,Uninsured,Obesity,167.7,83.8,121,58,94,2023-01-20
748,PT100748,Ahmed,Martinez,Male,94,A-,NY,Never,Medicare,Anxiety Disorder,191.5,54.0,129,82,77,2023-12-19
877,PT100877,Ahmed,Silva,Female,23,O+,NC,Current,Private,Depression,177.5,29.0,115,87,96,2024-06-02
885,PT100885,Ahmed,Williams,Female,44,O+,IL,Never,Private,Hypertension,162.5,69.2,166,77,86,2023-10-24
888,PT100888,Ahmed,Brown,Female,16,A+,VA,Current,Uninsured,Hypertension,154.3,81.9,109,93,73,2023-06-14
931,PT100931,Ahmed,Patel,Female,80,A+,OH,Former,Private,COPD,159.8,79.4,129,103,63,2023-12-30
985,PT100985,Ahmed,Nguyen,Male,23,O+,OH,Never,Medicaid,Type 2 Diabetes,170.4,91.6,130,57,96,2024-07-20
989,PT100989,Ahmed,Thompson,Male,64,B+,FL,Current,Medicare,Osteoarthritis,NaN,75.4,142,112,70,2023-01-31
1091,PT101091,Ahmed,White,Male,60,O-,NC,Former,Private,Depression,170.3,87.0,131,87,88,2023-10-17
1105,PT101105,Ahmed,Rossi,Male,84,O+,AZ,Never,Medicare,Type 2 Diabetes,187.6,78.7,94,56,65,2024-05-16
1113,PT101113,Ahmed,Khan,Male,13,O+,CA,Never,Medicare,Coronary Artery Disease,171.6,75.3,154,82,75,2024-08-20
1176,PT101176,Ahmed,Martinez,Female,61,O+,NJ,Former,Private,Hypertension,173.2,53.4,102,84,86,2024-08-08

In [23]:
### Extra function which is not performed on the above data

### split and Get function

## Example----if there are names which include f, m, and l names and we want to split them into 3 columns then we use the following

P_c=pd.read_csv('E:\\code\\movies.csv')
P_c.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [33]:
P_c['genres'].str.split('|').str.get(0)

0          Action
1             War
2       Biography
3           Crime
4           Drama
          ...
1624        Drama
1625        Drama
1626       Comedy
1627       Action
1628        Drama
Name: genres, Length: 1629, dtype: object

In [ ]:
## suppose in a dataset there is column of name of people, and names have variable words
### some have 2, some, 4, some 6, and also there is salutaion 'Mr, Mrs, Dr etc'

### in that case se will use something like

df['Name'].str.split(',').str.get(0)          ### this will give the word in name at '0' index after split
df['Name'].str.split(',').str.get(0).str.strip().str.split(' ', n=1)   ####  this will give strip the space and between first two words
df['Name'].str.split(',').str.get(0).str.strip().str.split(' ', n=2)   ####  will strip the space and between first two words
df['Name'].str.split(',').str.get(0).str.strip().str.split(' ', n=2, expand=True) ####  can create new columns for last, middle, title, etc

###  This is the power of Vectorised operations

###  suppose we have Miss, Ms etc 'similar words in title', we can replace into one

df['title']=df['title'].str.replace('Ms', 'Miss')
df['title']=df['title'].str.replace('Mlle', 'Miss')

In [47]:
###   Slicing


P_record['first_name'].str[:4]

0       Sara
1       Jess
2       John
3       Robe
4       Priy
        ...
1195    Eliz
1196    Jose
1197    Patr
1198    John
1199    Susa
Name: first_name, Length: 1200, dtype: str

In [48]:
P_record['first_name'].str[::2]

0         Srh
1        Jsia
2          Jh
3         Rbr
4         Pia
        ...
1195    Eiaeh
1196      Jsp
1197     Ptii
1198       Jh
1199      Ssn
Name: first_name, Length: 1200, dtype: str

###  Timestamp Objects ---> called as particular time moment

### vectorised data time operations

In [49]:
## making timestamp

pd.Timestamp('2026/07/14')   ### '/' or ',', or '-'   all will give same

Timestamp('2026-07-14 00:00:00')

In [50]:
type(pd.Timestamp('2026/07/14'))

pandas.Timestamp

In [51]:
pd.Timestamp('2026')      #### automatically assigns the first day of the year

Timestamp('2026-01-01 00:00:00')

In [52]:
pd.Timestamp('5th January 2026')

Timestamp('2026-01-05 00:00:00')

In [54]:
pd.Timestamp('14th July 2026, 3:55PM')

Timestamp('2026-07-14 15:55:00')

### using the python datetime object

In [56]:
import datetime as dt

dt.datetime(2026, 7, 14, 3, 57)

datetime.datetime(2026, 7, 14, 3, 57)

In [57]:
pd.Timestamp(dt.datetime(2026, 7, 14, 3, 57))

Timestamp('2026-07-14 03:57:00')

###  Benifits of making timestamp ---> can fetch any value

In [61]:
x=pd.Timestamp(dt.datetime(2026, 7, 14, 3, 57))
x.year

2026

In [60]:
x.month

7

In [62]:
x.hour

3

###  why Timestamp if datetime is already there

In [ ]:
#   doesnt work with huge data
##  syntax is convinient
###

### for storing multiple date---> collection of timestamp

### bunch of datetime ---> uses datetime index

In [63]:
pd.DatetimeIndex(['2026/07/14', '2026/07/15', '2026/07/19'])

DatetimeIndex(['2026-07-14', '2026-07-15', '2026-07-19'], dtype='datetime64[us]', freq=None)

In [64]:
pd.DatetimeIndex([dt.datetime(2026, 7, 14), dt.datetime(2026, 7, 12), dt.datetime(2026, 7, 11), dt.datetime(2026, 7, 10)])

DatetimeIndex(['2026-07-14', '2026-07-12', '2026-07-11', '2026-07-10'], dtype='datetime64[us]', freq=None)

In [65]:
pd.DatetimeIndex([pd.Timestamp(2026, 7, 14), pd.Timestamp(2026, 7, 12), pd.Timestamp(2026, 7, 11), pd.Timestamp(2026, 7, 10)])

DatetimeIndex(['2026-07-14', '2026-07-12', '2026-07-11', '2026-07-10'], dtype='datetime64[us]', freq=None)

In [66]:
g=pd.DatetimeIndex([pd.Timestamp(2026, 7, 14), pd.Timestamp(2026, 7, 12), pd.Timestamp(2026, 7, 11), pd.Timestamp(2026, 7, 10)])
pd.Series([1,4,7,9], index=g)

2026-07-14    1
2026-07-12    4
2026-07-11    7
2026-07-10    9
dtype: int64

### Date_range function

In [68]:
##  give a range of dates from 'start' to 'end'

pd.date_range(start='2026-07-14', end='2026-07-31', freq='D')

DatetimeIndex(['2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17',
               '2026-07-18', '2026-07-19', '2026-07-20', '2026-07-21',
               '2026-07-22', '2026-07-23', '2026-07-24', '2026-07-25',
               '2026-07-26', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31'],
              dtype='datetime64[us]', freq='D')

In [69]:
pd.date_range(start='2026-07-14', end='2026-07-31', freq='2D')  ###  '2D' gives the alternate dates

DatetimeIndex(['2026-07-14', '2026-07-16', '2026-07-18', '2026-07-20',
               '2026-07-22', '2026-07-24', '2026-07-26', '2026-07-28',
               '2026-07-30'],
              dtype='datetime64[us]', freq='2D')

In [70]:
###  only buisness days-------> no weekend days

pd.date_range(start='2026-07-14', end='2026-07-31', freq='B')

DatetimeIndex(['2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17',
               '2026-07-20', '2026-07-21', '2026-07-22', '2026-07-23',
               '2026-07-24', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31'],
              dtype='datetime64[us]', freq='B')

In [71]:
## only the one day of a week

pd.date_range(start='2026-07-14', end='2026-07-31', freq='W')

DatetimeIndex(['2026-07-19', '2026-07-26'], dtype='datetime64[us]', freq='W-SUN')

In [72]:
pd.date_range(start='2026-07-14', end='2026-07-31', freq='W-THU')   ###  only thursdays

DatetimeIndex(['2026-07-16', '2026-07-23', '2026-07-30'], dtype='datetime64[us]', freq='W-THU')

In [74]:
##  hourly date stamps

pd.date_range(start='2026-07-14', end='2026-07-31', freq='h')

DatetimeIndex(['2026-07-14 00:00:00', '2026-07-14 01:00:00',
               '2026-07-14 02:00:00', '2026-07-14 03:00:00',
               '2026-07-14 04:00:00', '2026-07-14 05:00:00',
               '2026-07-14 06:00:00', '2026-07-14 07:00:00',
               '2026-07-14 08:00:00', '2026-07-14 09:00:00',
               ...
               '2026-07-30 15:00:00', '2026-07-30 16:00:00',
               '2026-07-30 17:00:00', '2026-07-30 18:00:00',
               '2026-07-30 19:00:00', '2026-07-30 20:00:00',
               '2026-07-30 21:00:00', '2026-07-30 22:00:00',
               '2026-07-30 23:00:00', '2026-07-31 00:00:00'],
              dtype='datetime64[us]', length=409, freq='h')

In [75]:
###  for every 6 hours

pd.date_range(start='2026-07-14', end='2026-07-31', freq='6h')

DatetimeIndex(['2026-07-14 00:00:00', '2026-07-14 06:00:00',
               '2026-07-14 12:00:00', '2026-07-14 18:00:00',
               '2026-07-15 00:00:00', '2026-07-15 06:00:00',
               '2026-07-15 12:00:00', '2026-07-15 18:00:00',
               '2026-07-16 00:00:00', '2026-07-16 06:00:00',
               '2026-07-16 12:00:00', '2026-07-16 18:00:00',
               '2026-07-17 00:00:00', '2026-07-17 06:00:00',
               '2026-07-17 12:00:00', '2026-07-17 18:00:00',
               '2026-07-18 00:00:00', '2026-07-18 06:00:00',
               '2026-07-18 12:00:00', '2026-07-18 18:00:00',
               '2026-07-19 00:00:00', '2026-07-19 06:00:00',
               '2026-07-19 12:00:00', '2026-07-19 18:00:00',
               '2026-07-20 00:00:00', '2026-07-20 06:00:00',
               '2026-07-20 12:00:00', '2026-07-20 18:00:00',
               '2026-07-21 00:00:00', '2026-07-21 06:00:00',
               '2026-07-21 12:00:00', '2026-07-21 18:00:00',
               '2026-07-22 00:00:00', '2026-07-22 06:00:00',
               '2026-07-22 12:00:00', '2026-07-22 18:00:00',
               '2026-07-23 00:00:00', '2026-07-23 06:00:00',
               '2026-07-23 12:00:00', '2026-07-23 18:00:00',
               '2026-07-24 00:00:00', '2026-07-24 06:00:00',
               '2026-07-24 12:00:00', '2026-07-24 18:00:00',
               '2026-07-25 00:00:00', '2026-07-25 06:00:00',
               '2026-07-25 12:00:00', '2026-07-25 18:00:00',
               '2026-07-26 00:00:00', '2026-07-26 06:00:00',
               '2026-07-26 12:00:00', '2026-07-26 18:00:00',
               '2026-07-27 00:00:00', '2026-07-27 06:00:00',
               '2026-07-27 12:00:00', '2026-07-27 18:00:00',
               '2026-07-28 00:00:00', '2026-07-28 06:00:00',
               '2026-07-28 12:00:00', '2026-07-28 18:00:00',
               '2026-07-29 00:00:00', '2026-07-29 06:00:00',
               '2026-07-29 12:00:00', '2026-07-29 18:00:00',
               '2026-07-30 00:00:00', '2026-07-30 06:00:00',
               '2026-07-30 12:00:00', '2026-07-30 18:00:00',
               '2026-07-31 00:00:00'],
              dtype='datetime64[us]', freq='6h')

In [77]:
### only month end date

pd.date_range(start='2026-07-14', end='2026-07-31', freq='ME')

DatetimeIndex(['2026-07-31'], dtype='datetime64[us]', freq='ME')

In [ ]:
###  only month start date

pd.date_range(start='2026-07-14', end='2026-07-31', freq='ME')

In [80]:
###  only year end date

pd.date_range(start='2026-07-14', end='2032-07-31', freq='YE')

DatetimeIndex(['2026-12-31', '2027-12-31', '2028-12-31', '2029-12-31',
               '2030-12-31', '2031-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [81]:
###  using periods(number of results)

pd.date_range(start='2026-07-14', periods=25, freq='D')

DatetimeIndex(['2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17',
               '2026-07-18', '2026-07-19', '2026-07-20', '2026-07-21',
               '2026-07-22', '2026-07-23', '2026-07-24', '2026-07-25',
               '2026-07-26', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31', '2026-08-01', '2026-08-02',
               '2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06',
               '2026-08-07'],
              dtype='datetime64[us]', freq='D')

In [82]:
###  using periods(number of results)----> hourly

pd.date_range(start='2026-07-14', periods=25, freq='h')

DatetimeIndex(['2026-07-14 00:00:00', '2026-07-14 01:00:00',
               '2026-07-14 02:00:00', '2026-07-14 03:00:00',
               '2026-07-14 04:00:00', '2026-07-14 05:00:00',
               '2026-07-14 06:00:00', '2026-07-14 07:00:00',
               '2026-07-14 08:00:00', '2026-07-14 09:00:00',
               '2026-07-14 10:00:00', '2026-07-14 11:00:00',
               '2026-07-14 12:00:00', '2026-07-14 13:00:00',
               '2026-07-14 14:00:00', '2026-07-14 15:00:00',
               '2026-07-14 16:00:00', '2026-07-14 17:00:00',
               '2026-07-14 18:00:00', '2026-07-14 19:00:00',
               '2026-07-14 20:00:00', '2026-07-14 21:00:00',
               '2026-07-14 22:00:00', '2026-07-14 23:00:00',
               '2026-07-15 00:00:00'],
              dtype='datetime64[us]', freq='h')

In [83]:
###  using periods(number of results)-----> every 6hours

pd.date_range(start='2026-07-14', periods=25, freq='6h')

DatetimeIndex(['2026-07-14 00:00:00', '2026-07-14 06:00:00',
               '2026-07-14 12:00:00', '2026-07-14 18:00:00',
               '2026-07-15 00:00:00', '2026-07-15 06:00:00',
               '2026-07-15 12:00:00', '2026-07-15 18:00:00',
               '2026-07-16 00:00:00', '2026-07-16 06:00:00',
               '2026-07-16 12:00:00', '2026-07-16 18:00:00',
               '2026-07-17 00:00:00', '2026-07-17 06:00:00',
               '2026-07-17 12:00:00', '2026-07-17 18:00:00',
               '2026-07-18 00:00:00', '2026-07-18 06:00:00',
               '2026-07-18 12:00:00', '2026-07-18 18:00:00',
               '2026-07-19 00:00:00', '2026-07-19 06:00:00',
               '2026-07-19 12:00:00', '2026-07-19 18:00:00',
               '2026-07-20 00:00:00'],
              dtype='datetime64[us]', freq='6h')

###   to_datetime function

In [86]:
##  converting the dtypes to datetime--- > to pandas timestamp

P_record['last_admission_date']=pd.to_datetime(P_record['last_admission_date'])

In [87]:
P_record.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1200 non-null   str
 1   first_name           1200 non-null   str
 2   last_name            1200 non-null   str
 3   gender               1200 non-null   str
 4   age                  1200 non-null   int64
 5   blood_type           1145 non-null   str
 6   state                1200 non-null   str
 7   smoking_status       1148 non-null   str
 8   insurance_type       1200 non-null   str
 9   primary_condition    1195 non-null   str
 10  height_cm            1147 non-null   float64
 11  weight_kg            1152 non-null   float64
 12  systolic_bp          1200 non-null   int64
 13  diastolic_bp         1200 non-null   int64
 14  heart_rate_bpm       1200 non-null   int64
 15  last_admission_date  1200 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(4), str(9)
memory usage: 150.1 KB

In [88]:
###  for converting the datetime values which are present in other type of datatype

pd.to_datetime(P_record['last_admission_date']).dt.day_name()

0          Friday
1        Thursday
2       Wednesday
3       Wednesday
4          Friday
          ...
1195     Thursday
1196     Saturday
1197       Friday
1198     Saturday
1199       Sunday
Name: last_admission_date, Length: 1200, dtype: str

In [93]:
###  with error in date formats etc---> not a time

s=pd.Series(['2026-07-14', '2026-07-14', '2026-07-14', '2026-07-34'])
pd.to_datetime(s, errors='coerce').dt.year  ###   it will skip the wrong format date

0    2026.0
1    2026.0
2    2026.0
3       NaN
dtype: float64

In [91]:
s=pd.Series(['2026-07-14', '2026-07-14', '2026-07-14', '2026-07-34'])
pd.to_datetime(s, errors='coerce').dt.month_name()

0    July
1    July
2    July
3     NaN
dtype: str

In [94]:
## check the quater end  

P_record['last_admission_date'].dt.is_quarter_end

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: last_admission_date, Length: 1200, dtype: bool

In [95]:
## check the month end  

P_record['last_admission_date'].dt.is_month_end

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: last_admission_date, Length: 1200, dtype: bool